/* ===========================================================
   Données du site — Mon Périple Vidéoludique
   Un objet par console. "games" est trié par date de sortie.
   score / scoreType: scoreType "user" = note utilisateurs
   Metacritic (x10, ex. 8.9 -> 89) ; "critic" = Metascore critique
   utilisé quand la note utilisateurs n'est pas disponible ;
   null = aucune note Metacritic (ex. sortie Japon uniquement).
   =========================================================== */

const DATA = {
  consoles: {
    gba: {
      key: "gba",
      name: "Game Boy Advance",
      short: "GBA",
      color: "#8fae52",
      theme: "assets/theme-gba.css",
      page: "gba.html",
      ready: true,
      games: [
        {slug:"advance-wars", title:"Advance Wars", date:"2001-09-09", score:86, scoreType:"user", hltb:"14h", blurb:"Stratégie tour par tour culte qui a lancé toute une série."},
        {slug:"golden-sun", title:"Golden Sun", date:"2001-11-11", score:89, scoreType:"user", hltb:"19h", blurb:"RPG au tour par tour avec un système de Psynergie marquant."},
        {slug:"klonoa-empire-of-dreams", title:"Klonoa: Empire of Dreams", date:"2001-11-14", score:79, scoreType:"critic", hltb:"5h", blurb:"Plateforme onirique signée Namco, charme et level design soignés."},
        {slug:"wario-land-4", title:"Wario Land 4", date:"2001-11-18", score:87, scoreType:"user", hltb:"6h", blurb:"Plateforme non-linéaire à la direction artistique et sonore culte."},
        {slug:"tactics-ogre-the-knight-of-lodis", title:"Tactics Ogre: The Knight of Lodis", date:"2001-11-21", score:82, scoreType:"critic", hltb:"35h", blurb:"Tactical-RPG exigeant, préquelle des épisodes SNES/N64."},
        {slug:"sonic-advance", title:"Sonic Advance", date:"2002-02-19", score:79, scoreType:"critic", hltb:"4h", blurb:"Le retour du hérisson en 2D par Dimps, vitesse et level design réussis."},
        {slug:"fire-emblem-the-binding-blade", title:"Fire Emblem: The Binding Blade", date:"2002-03-29", score:null, scoreType:"none", hltb:"22h", blurb:"L'épisode de Roy, resté au Japon, préquelle directe de notre premier Fire Emblem."},
        {slug:"zone-of-the-enders-fist-of-mars", title:"Zone of the Enders: The Fist of Mars", date:"2002-04-30", score:74, scoreType:"critic", hltb:"30h", blurb:"Tactical-RPG de mechas produit par Kojima, récit dense sur Mars."},
        {slug:"mega-man-zero", title:"Mega Man Zero", date:"2002-09-09", score:78, scoreType:"critic", hltb:"5h", blurb:"Zero reprend le flambeau dans une série d'action stylée et exigeante."},
        {slug:"lunar-legend", title:"Lunar Legend", date:"2002-11-19", score:71, scoreType:"critic", hltb:"20h", blurb:"Le JRPG culte de Game Arts condensé pour la portable."},
        {slug:"zelda-a-link-to-the-past-four-swords", title:"The Legend of Zelda: A Link to the Past & Four Swords", date:"2002-12-03", score:88, scoreType:"user", hltb:"10h", blurb:"Le classique SNES plus un mode multijoueur inédit, Four Swords."},
        {slug:"kirby-nightmare-in-dream-land", title:"Kirby: Nightmare in Dream Land", date:"2002-12-16", score:79, scoreType:"critic", hltb:"5h", blurb:"Remake du tout premier Kirby, doux et accessible."},
        {slug:"sonic-advance-2", title:"Sonic Advance 2", date:"2002-12-20", score:80, scoreType:"critic", hltb:"4h", blurb:"Suite plus rapide et plus exigeante, Tiny Chao Garden inclus."},
        {slug:"golden-sun-the-lost-age", title:"Golden Sun: The Lost Age", date:"2003-04-14", score:89, scoreType:"user", hltb:"24h", blurb:"Suite directe de Golden Sun, poursuite de l'aventure et des Psynergies."},
        {slug:"ninja-five-o", title:"Ninja Five-O", date:"2003-04-22", score:82, scoreType:"critic", hltb:"4h", blurb:"Ninja, grappin et otages : pépite d'action devenue pièce de collection."},
        {slug:"donkey-kong-country", title:"Donkey Kong Country", date:"2003-06-09", score:87, scoreType:"user", hltb:"8h", blurb:"Portage du classique SNES, toujours aussi solide."},
        {slug:"dragon-ball-z-legacy-of-goku-2", title:"Dragon Ball Z: The Legacy of Goku II", date:"2003-06-17", score:88, scoreType:"user", hltb:"12h", blurb:"Action-RPG dans l'univers DBZ, de la saga Cell à Buu."},
        {slug:"mega-man-battle-network-3", title:"Mega Man Battle Network 3", date:"2003-06-18", score:83, scoreType:"critic", hltb:"18h", blurb:"RPG tactique en réseau, l'un des sommets de la série."},
        {slug:"advance-wars-2-black-hole-rising", title:"Advance Wars 2: Black Hole Rising", date:"2003-06-23", score:88, scoreType:"critic", hltb:"15h", blurb:"Suite plus équilibrée, avec une nouvelle campagne solo."},
        {slug:"boktai-the-sun-is-in-your-hand", title:"Boktai: The Sun Is in Your Hand", date:"2003-09-29", score:76, scoreType:"critic", hltb:"12h", blurb:"Chasseur de vampires avec un capteur solaire intégré à la cartouche."},
        {slug:"onimusha-tactics", title:"Onimusha Tactics", date:"2003-10-28", score:72, scoreType:"critic", hltb:"30h", blurb:"L'univers samouraï de Capcom décliné en tactical-RPG portable."},
        {slug:"fire-emblem", title:"Fire Emblem", date:"2003-11-03", score:89, scoreType:"user", hltb:"25h", blurb:"Premier épisode occidental de la saga, tactique et permadeath."},
        {slug:"sword-of-mana", title:"Sword of Mana", date:"2003-11-11", score:71, scoreType:"critic", hltb:"15h", blurb:"Remake de Seiken Densetsu, deux personnages jouables au choix."},
        {slug:"mario-and-luigi-superstar-saga", title:"Mario & Luigi: Superstar Saga", date:"2003-11-17", score:86, scoreType:"user", hltb:"15h", blurb:"RPG humoristique en duo, combos et timing à la clé."},
        {slug:"kingdom-hearts-chain-of-memories", title:"Kingdom Hearts: Chain of Memories", date:"2003-12-07", score:82, scoreType:"critic", hltb:"13h", blurb:"Spin-off à système de cartes, entre deux épisodes canoniques."},
        {slug:"mega-man-zero-3", title:"Mega Man Zero 3", date:"2004-04-15", score:81, scoreType:"critic", hltb:"4h", blurb:"Troisième volet, affine la formule sans bouleverser l'équilibre."},
        {slug:"river-city-ransom-ex", title:"River City Ransom EX", date:"2004-05-25", score:80, scoreType:"critic", hltb:"6h", blurb:"Baston, RPG et sushis dans les rues de River City, culte NES modernisé."},
        {slug:"shining-force-resurrection-of-the-dark-dragon", title:"Shining Force: Resurrection of the Dark Dragon", date:"2004-06-08", score:78, scoreType:"critic", hltb:"20h", blurb:"Remake soigné du tactical fondateur de Sega."},
        {slug:"astro-boy-omega-factor", title:"Astro Boy: Omega Factor", date:"2004-08-17", score:85, scoreType:"critic", hltb:"4h", blurb:"Beat'em up signé Treasure, hommage complet à l'oeuvre de Tezuka."},
        {slug:"pokemon-firered-leafgreen", title:"Pokémon FireRed / LeafGreen", date:"2004-09-07", score:85, scoreType:"user", hltb:"24h", blurb:"Remake de la toute première génération Pokémon."},
        {slug:"dragon-ball-z-buus-fury", title:"Dragon Ball Z: Buu's Fury", date:"2004-09-14", score:86, scoreType:"user", hltb:"15h", blurb:"Suite directe de Legacy of Goku II, jusqu'à la saga Buu."},
        {slug:"boktai-2-solar-boy-django", title:"Boktai 2: Solar Boy Django", date:"2004-09-28", score:77, scoreType:"critic", hltb:"12h", blurb:"Suite du chasseur de vampires au capteur solaire, imaginée par Kojima."},
        {slug:"donkey-kong-country-2-diddys-kong-quest", title:"Donkey Kong Country 2: Diddy's Kong Quest", date:"2004-11-15", score:88, scoreType:"user", hltb:"9h", blurb:"Portage du meilleur épisode SNES de la trilogie DKC."},
        {slug:"zelda-the-minish-cap", title:"The Legend of Zelda: The Minish Cap", date:"2005-01-10", score:88, scoreType:"user", hltb:"11h", blurb:"Link rétrécit pour explorer un monde miniature, très bien noté."},
        {slug:"pokemon-emerald", title:"Pokémon Emerald", date:"2005-04-30", score:88, scoreType:"user", hltb:"24h", blurb:"Version augmentée de Ruby/Sapphire, contenu post-jeu étoffé."},
        {slug:"fire-emblem-the-sacred-stones", title:"Fire Emblem: The Sacred Stones", date:"2005-05-23", score:87, scoreType:"user", hltb:"20h", blurb:"Dernier Fire Emblem GBA, jumeaux royaux et monde ouvert."},
        {slug:"boktai-3-sabatas-counterattack", title:"Boktai 3: Sabata's Counterattack", date:"2005-06-23", score:null, scoreType:"none", hltb:"12h", blurb:"Conclusion de la trilogie solaire de Kojima, restée au Japon."},
        {slug:"riviera-the-promised-land", title:"Riviera: The Promised Land", date:"2005-06-28", score:76, scoreType:"critic", hltb:"20h", blurb:"RPG atypique de Sting, exploration condensée et quatre héroïnes à lier."},
        {slug:"sigma-star-saga", title:"Sigma Star Saga", date:"2005-08-16", score:71, scoreType:"critic", hltb:"15h", blurb:"RPG et shoot'em up entremêlés, curiosité signée WayForward."},
        {slug:"rebelstar-tactical-command", title:"Rebelstar: Tactical Command", date:"2005-09-06", score:77, scoreType:"critic", hltb:"15h", blurb:"Tactique par les créateurs de X-COM, taillée pour la portable."},
        {slug:"mega-man-zero-4", title:"Mega Man Zero 4", date:"2005-09-27", score:75, scoreType:"critic", hltb:"5h", blurb:"Conclusion de la saga Zero, entre résistance humaine et cyber-elfes."},
        {slug:"klonoa-dream-champ-tournament", title:"Klonoa: Dream Champ Tournament", date:"2005-11-08", score:74, scoreType:"critic", hltb:"6h", blurb:"Klonoa rappelé au pays des rêves pour un tournoi, plateforme-puzzle raffinée."},
        {slug:"mega-man-battle-network-6", title:"Mega Man Battle Network 6", date:"2005-11-14", score:76, scoreType:"critic", hltb:"20h", blurb:"Ultime épisode de la saga réseau, la formule à son apogée."},
        {slug:"pokemon-mystery-dungeon-red-rescue-team", title:"Pokémon Mystery Dungeon: Red Rescue Team", date:"2005-11-17", score:71, scoreType:"critic", hltb:"20h", blurb:"Donjons procéduraux : incarnez un Pokémon dans un monde de Pokémon."},
        {slug:"tales-of-phantasia-gba", title:"Tales of Phantasia", date:"2006-03-07", score:73, scoreType:"critic", hltb:"30h", blurb:"Le premier Tales enfin traduit, voyage temporel et combats en ligne."},
        {slug:"mother-3", title:"Mother 3", date:"2006-04-20", score:null, scoreType:"none", hltb:"20h", blurb:"Suite culte d'Earthbound, jamais sortie officiellement hors Japon."},
        {slug:"dragon-ball-advanced-adventure", title:"Dragon Ball: Advanced Adventure", date:"2006-06-06", score:86, scoreType:"user", hltb:"6h", blurb:"Retour aux origines de Dragon Ball, l'enfance de Goku."},
        {slug:"summon-night-swordcraft-story", title:"Summon Night: Swordcraft Story", date:"2006-07-25", score:74, scoreType:"critic", hltb:"20h", blurb:"Action-RPG de forgeron où l'on fabrique chacune de ses armes."},
        {slug:"summon-night-swordcraft-story-2", title:"Summon Night: Swordcraft Story 2", date:"2006-11-14", score:75, scoreType:"critic", hltb:"20h", blurb:"Suite plus généreuse, forge et duels affinés."},
        {slug:"yggdra-union", title:"Yggdra Union", date:"2006-11-21", score:77, scoreType:"critic", hltb:"30h", blurb:"Tactical-RPG à cartes de Sting, exigeant et singulier."}
      ]
    },

    ds: {
      key: "ds",
      name: "Nintendo DS",
      short: "DS",
      color: "#3d6a91",
      theme: "assets/theme-ds.css",
      page: "ds.html",
      ready: true,
      games: [
        {slug:"advance-wars-dual-strike", title:"Advance Wars: Dual Strike", date:"2005-08-22", score:88, scoreType:"user", hltb:"25h", blurb:"La stratégie culte passe sur deux écrans avec les duos de généraux."},
        {slug:"another-code-two-memories", title:"Another Code: Two Memories", date:"2005-09-26", score:66, scoreType:"critic", hltb:"6h", blurb:"Ashley enquête sur son père disparu, aventure narrative signée Cing."},
        {slug:"trauma-center-under-the-knife", title:"Trauma Center: Under the Knife", date:"2005-10-04", score:77, scoreType:"critic", hltb:"8h", blurb:"Chirurgie au stylet sous tension, opérations impossibles et virus mystérieux."},
        {slug:"sonic-rush", title:"Sonic Rush", date:"2005-11-15", score:82, scoreType:"critic", hltb:"4h", blurb:"Sonic à toute vitesse sur deux écrans, avec Blaze et la jauge de boost."},
        {slug:"mario-and-luigi-partners-in-time", title:"Mario & Luigi: Partners in Time", date:"2005-11-28", score:85, scoreType:"user", hltb:"17h", blurb:"Les frères voyagent dans le temps aux côtés de leurs versions bébés."},
        {slug:"contact", title:"Contact", date:"2006-10-19", score:71, scoreType:"critic", hltb:"25h", blurb:"RPG méta de Grasshopper où le Professeur vous parle à travers l'écran."},
        {slug:"magical-starsign", title:"Magical Starsign", date:"2006-10-23", score:71, scoreType:"critic", hltb:"30h", blurb:"RPG spatial coloré de Brownie Brown, six élèves à travers les planètes."},
        {slug:"hotel-dusk-room-215", title:"Hotel Dusk: Room 215", date:"2007-01-22", score:78, scoreType:"critic", hltb:"15h", blurb:"Polar interactif au crayonné unique, console tenue comme un livre."},
        {slug:"zelda-phantom-hourglass", title:"The Legend of Zelda: Phantom Hourglass", date:"2007-10-01", score:90, scoreType:"critic", hltb:"15h", blurb:"Suite directe de Wind Waker, entièrement jouée au stylet."},
        {slug:"advance-wars-days-of-ruin", title:"Advance Wars: Days of Ruin", date:"2008-01-21", score:86, scoreType:"critic", hltb:"25h", blurb:"Advance Wars post-apocalyptique, plus sombre et rééquilibré."},
        {slug:"shiren-the-wanderer", title:"Mystery Dungeon: Shiren the Wanderer", date:"2008-02-05", score:78, scoreType:"critic", hltb:"40h", blurb:"Roguelike japonais exigeant, chaque mort renvoie au premier étage."},
        {slug:"professor-layton-curious-village", title:"Professeur Layton et l'Étrange Village", date:"2008-02-10", score:88, scoreType:"user", hltb:"12h", blurb:"Énigmes élégantes et village mystérieux, naissance d'une série culte."},
        {slug:"soma-bringer", title:"Soma Bringer", date:"2008-02-28", score:null, scoreType:"none", hltb:"25h", blurb:"L'action-RPG de Monolith Soft resté au Japon, pensé pour le jeu à trois."},
        {slug:"the-world-ends-with-you", title:"The World Ends with You", date:"2008-04-22", score:90, scoreType:"user", hltb:"20h", blurb:"RPG d'action ultra-stylé dans Shibuya, combats sur les deux écrans."},
        {slug:"kirby-super-star-ultra", title:"Kirby Super Star Ultra", date:"2008-09-22", score:89, scoreType:"user", hltb:"8h", blurb:"Remake de Super Star et ses nombreux modes, l'un des meilleurs Kirby."},
        {slug:"time-hollow", title:"Time Hollow", date:"2008-09-30", score:70, scoreType:"critic", hltb:"10h", blurb:"Un stylo perce des trous dans le temps pour réécrire les disparitions."},
        {slug:"luminous-arc-2", title:"Luminous Arc 2", date:"2008-11-04", score:71, scoreType:"critic", hltb:"30h", blurb:"Tactical-RPG de sorcières aux liens à cultiver entre les batailles."},
        {slug:"chrono-trigger", title:"Chrono Trigger", date:"2008-11-25", score:91, scoreType:"user", hltb:"23h", blurb:"Le voyage temporel légendaire de la SNES, enfin portable."},
        {slug:"fire-emblem-shadow-dragon", title:"Fire Emblem: Shadow Dragon", date:"2009-02-16", score:81, scoreType:"critic", hltb:"20h", blurb:"Remake du tout premier Fire Emblem, avec Marth."},
        {slug:"nostalgia", title:"Nostalgia", date:"2009-02-24", score:71, scoreType:"critic", hltb:"30h", blurb:"Tour du monde en dirigeable dans un XIXe siècle fantastique."},
        {slug:"gta-chinatown-wars", title:"Grand Theft Auto: Chinatown Wars", date:"2009-03-17", score:93, scoreType:"critic", hltb:"12h", blurb:"GTA vu du dessus étonnamment complet, taillé sur mesure pour la DS."},
        {slug:"henry-hatsworth", title:"Henry Hatsworth in the Puzzling Adventure", date:"2009-03-17", score:79, scoreType:"critic", hltb:"10h", blurb:"Moitié plateforme, moitié puzzle, un gentleman contre le Monde Étrange."},
        {slug:"suikoden-tierkreis", title:"Suikoden Tierkreis", date:"2009-03-17", score:78, scoreType:"critic", hltb:"30h", blurb:"Les 108 étoiles du destin en poche, dans un multivers inédit."},
        {slug:"pokemon-platinum", title:"Pokémon Platine", date:"2009-03-22", score:88, scoreType:"user", hltb:"40h", blurb:"Version définitive de Sinnoh, avec le Monde Distorsion."},
        {slug:"the-dark-spire", title:"The Dark Spire", date:"2009-04-14", score:74, scoreType:"critic", hltb:"30h", blurb:"Dungeon-RPG à l'ancienne, austère et fier de l'être."},
        {slug:"knights-in-the-nightmare", title:"Knights in the Nightmare", date:"2009-06-02", score:80, scoreType:"critic", hltb:"25h", blurb:"Hybride de tactical-RPG et de shoot'em up signé Sting, unique en son genre."},
        {slug:"professor-layton-diabolical-box", title:"Professeur Layton et la Boîte de Pandore", date:"2009-08-24", score:84, scoreType:"critic", hltb:"13h", blurb:"Deuxième enquête du professeur, à bord du Molentary Express."},
        {slug:"mario-and-luigi-bowsers-inside-story", title:"Mario & Luigi: Voyage au centre de Bowser", date:"2009-09-14", score:89, scoreType:"user", hltb:"25h", blurb:"Mario et Luigi explorent l'intérieur de Bowser, sommet de la série."},
        {slug:"pokemon-mystery-dungeon-explorers-of-sky", title:"Pokémon Donjon Mystère: Explorateurs du Ciel", date:"2009-10-12", score:86, scoreType:"user", hltb:"35h", blurb:"Version ultime d'Explorateurs, l'histoire Pokémon la plus émouvante."},
        {slug:"might-and-magic-clash-of-heroes", title:"Might & Magic: Clash of Heroes", date:"2009-12-01", score:87, scoreType:"critic", hltb:"18h", blurb:"Puzzle-RPG à campagne complète, cinq héros et autant de styles."},
        {slug:"zelda-spirit-tracks", title:"The Legend of Zelda: Spirit Tracks", date:"2009-12-07", score:87, scoreType:"critic", hltb:"18h", blurb:"Link conducteur de train, accompagné du fantôme de la princesse Zelda."},
        {slug:"glory-of-heracles", title:"Glory of Heracles", date:"2010-01-18", score:71, scoreType:"critic", hltb:"30h", blurb:"Mythologie grecque et immortels amnésiques, écrit par la plume de Mother."},
        {slug:"pokemon-heartgold-soulsilver", title:"Pokémon HeartGold / SoulSilver", date:"2010-03-14", score:90, scoreType:"user", hltb:"40h", blurb:"Remake de la deuxième génération, Johto et Kanto réunis, Pokéwalker inclus."},
        {slug:"infinite-space", title:"Infinite Space", date:"2010-03-16", score:78, scoreType:"critic", hltb:"60h", blurb:"Space opera tentaculaire de PlatinumGames, flottes à composer et récit fleuve."},
        {slug:"smt-strange-journey", title:"Shin Megami Tensei: Strange Journey", date:"2010-03-23", score:80, scoreType:"critic", hltb:"40h", blurb:"Expédition SMT pure et dure en Antarctique, sombre et fascinante."},
        {slug:"lufia-curse-of-the-sinistrals", title:"Lufia: Curse of the Sinistrals", date:"2010-08-31", score:77, scoreType:"critic", hltb:"25h", blurb:"Remake en action-RPG du classique SNES, rythmé et généreux."},
        {slug:"professor-layton-unwound-future", title:"Professeur Layton et le Destin Perdu", date:"2010-09-12", score:89, scoreType:"user", hltb:"12h", blurb:"Le voyage dans le temps le plus émouvant du professeur."},
        {slug:"last-window-the-secret-of-cape-west", title:"Last Window: The Secret of Cape West", date:"2010-09-17", score:77, scoreType:"critic", hltb:"12h", blurb:"La suite de Hotel Dusk, polar feutré sorti uniquement en Europe."},
        {slug:"etrian-odyssey-3-the-drowned-city", title:"Etrian Odyssey III: The Drowned City", date:"2010-09-21", score:79, scoreType:"critic", hltb:"60h", blurb:"Labyrinthe englouti et cartographie au stylet, pour explorateurs patients."},
        {slug:"rune-factory-3", title:"Rune Factory 3", date:"2010-11-09", score:80, scoreType:"critic", hltb:"50h", blurb:"Donjons, ferme et romance : l'épisode DS le plus abouti de la série."},
        {slug:"999-nine-hours-nine-persons-nine-doors", title:"999: Nine Hours, Nine Persons, Nine Doors", date:"2010-11-16", score:90, scoreType:"user", hltb:"10h", blurb:"Visual novel à énigmes sous tension, neuf personnes piégées sur un navire."},
        {slug:"ghost-trick-phantom-detective", title:"Ghost Trick: Phantom Detective", date:"2011-01-11", score:90, scoreType:"user", hltb:"12h", blurb:"Sitôt mort, Sissel manipule les objets pour changer le destin des vivants."},
        {slug:"pokemon-black-white", title:"Pokémon Noir / Blanc", date:"2011-03-06", score:82, scoreType:"user", hltb:"32h", blurb:"Cinquième génération à Unys, avec uniquement de nouveaux Pokémon."},
        {slug:"okamiden", title:"Okamiden", date:"2011-03-15", score:78, scoreType:"critic", hltb:"20h", blurb:"Chibiterasu reprend le pinceau céleste dans une suite pleine de charme."},
        {slug:"kirby-mass-attack", title:"Kirby Mass Attack", date:"2011-09-19", score:83, scoreType:"critic", hltb:"7h", blurb:"Jusqu'à dix Kirby menés au stylet, inventif de bout en bout."},
        {slug:"solatorobo-red-the-hunter", title:"Solatorobo: Red the Hunter", date:"2011-09-27", score:77, scoreType:"critic", hltb:"15h", blurb:"Chasseur canin et mécha dans un archipel céleste, dix ans de fabrication."},
        {slug:"professor-layton-last-specter", title:"Professeur Layton et l'Appel du Spectre", date:"2011-10-17", score:78, scoreType:"critic", hltb:"15h", blurb:"Première enquête aux côtés de Luke, aux origines du duo."},
        {slug:"inazuma-eleven-2", title:"Inazuma Eleven 2", date:"2012-05-18", score:79, scoreType:"critic", hltb:"35h", blurb:"RPG de football contre des envahisseurs, deux versions au choix."},
        {slug:"pokemon-conquest", title:"Pokémon Conquest", date:"2012-06-18", score:80, scoreType:"critic", hltb:"30h", blurb:"Pokémon rencontre Nobunaga's Ambition, crossover tactique inattendu."},
        {slug:"inazuma-eleven-3", title:"Inazuma Eleven 3", date:"2013-09-27", score:76, scoreType:"critic", hltb:"40h", blurb:"Coupe du monde et techniques surpuissantes, conclusion de la trilogie."}
      ]
    },

    n3ds: {
      key: "n3ds",
      name: "Nintendo 3DS",
      short: "3DS",
      color: "#ff2ea6",
      theme: "assets/theme-3ds.css",
      page: "3ds.html",
      ready: true,
      games: [
        {slug:"zelda-ocarina-of-time-3d", title:"The Legend of Zelda: Ocarina of Time 3D", date:"2011-06-19", score:91, scoreType:"user", hltb:"26h", blurb:"Le chef-d'oeuvre N64 remis à neuf, avec la Master Quest en bonus."},
        {slug:"smt-devil-survivor-overclocked", title:"Shin Megami Tensei: Devil Survivor Overclocked", date:"2011-08-23", score:78, scoreType:"critic", hltb:"30h", blurb:"Le huis clos tactique de Tokyo, réédité avec voix et huitième jour."},
        {slug:"kid-icarus-uprising", title:"Kid Icarus: Uprising", date:"2012-03-23", score:87, scoreType:"user", hltb:"11h", blurb:"Le retour de Pit par Masahiro Sakurai, dialogues savoureux et action intense."},
        {slug:"kingdom-hearts-3d-dream-drop-distance", title:"Kingdom Hearts 3D: Dream Drop Distance", date:"2012-07-31", score:75, scoreType:"critic", hltb:"17h", blurb:"Sora et Riku alternent dans les mondes endormis, étape clé de l'intrigue."},
        {slug:"zero-escape-virtues-last-reward", title:"Zero Escape: Virtue's Last Reward", date:"2012-10-23", score:88, scoreType:"user", hltb:"30h", blurb:"Suite de 999, huis clos à embranchements où chaque trahison compte."},
        {slug:"professor-layton-miracle-mask", title:"Professeur Layton et le Masque des Miracles", date:"2012-10-28", score:81, scoreType:"critic", hltb:"15h", blurb:"Cinquième enquête du professeur, entre cirque et cité du désert."},
        {slug:"fire-emblem-awakening", title:"Fire Emblem: Awakening", date:"2013-02-04", score:89, scoreType:"user", hltb:"25h", blurb:"L'épisode qui a sauvé la série, avec mariages et enfants entre unités."},
        {slug:"etrian-odyssey-4", title:"Etrian Odyssey IV: Legends of the Titan", date:"2013-02-26", score:82, scoreType:"critic", hltb:"40h", blurb:"Dungeon-RPG où l'on dessine soi-même sa carte sur l'écran tactile."},
        {slug:"monster-hunter-3-ultimate", title:"Monster Hunter 3 Ultimate", date:"2013-03-19", score:85, scoreType:"critic", hltb:"50h", blurb:"La chasse aux monstres dans sa version la plus complète de l'ère Tri."},
        {slug:"luigis-mansion-dark-moon", title:"Luigi's Mansion: Dark Moon", date:"2013-03-24", score:84, scoreType:"user", hltb:"12h", blurb:"Luigi reprend l'aspirateur à fantômes à travers cinq manoirs variés."},
        {slug:"donkey-kong-country-returns-3d", title:"Donkey Kong Country Returns 3D", date:"2013-05-24", score:78, scoreType:"critic", hltb:"8h", blurb:"Le retour exigeant de la famille Kong, adapté du jeu Wii."},
        {slug:"project-x-zone", title:"Project X Zone", date:"2013-06-25", score:71, scoreType:"critic", hltb:"40h", blurb:"Crossover tactique délirant entre Capcom, Sega et Namco."},
        {slug:"shin-megami-tensei-4", title:"Shin Megami Tensei IV", date:"2013-07-16", score:83, scoreType:"critic", hltb:"45h", blurb:"Apocalypse démoniaque entre royaume médiéval et Tokyo en ruines."},
        {slug:"attack-of-the-friday-monsters", title:"Attack of the Friday Monsters!", date:"2013-07-18", score:81, scoreType:"critic", hltb:"3h", blurb:"Un été japonais où les monstres télé prennent vie, court et touchant."},
        {slug:"mario-and-luigi-dream-team", title:"Mario & Luigi: Dream Team", date:"2013-08-11", score:81, scoreType:"critic", hltb:"30h", blurb:"Les frères plongent dans les rêves de Luigi, démultiplié à l'infini."},
        {slug:"etrian-odyssey-untold-millennium-girl", title:"Etrian Odyssey Untold: The Millennium Girl", date:"2013-10-01", score:80, scoreType:"critic", hltb:"40h", blurb:"Le premier Etrian refait, avec un mode histoire scénarisé inédit."},
        {slug:"rune-factory-4", title:"Rune Factory 4", date:"2013-10-01", score:78, scoreType:"critic", hltb:"55h", blurb:"Ferme, romance et donjons, le mariage parfait des genres."},
        {slug:"pokemon-x-y", title:"Pokémon X / Y", date:"2013-10-12", score:84, scoreType:"user", hltb:"32h", blurb:"Le passage de Pokémon à la 3D, avec Kalos et les méga-évolutions."},
        {slug:"zelda-a-link-between-worlds", title:"The Legend of Zelda: A Link Between Worlds", date:"2013-11-22", score:90, scoreType:"user", hltb:"16h", blurb:"Hyrule d'A Link to the Past revisité, Link se fond dans les murs."},
        {slug:"bravely-default", title:"Bravely Default", date:"2014-02-07", score:84, scoreType:"user", hltb:"50h", blurb:"Le RPG old-school de Square Enix, avec son système Brave et Default."},
        {slug:"kirby-triple-deluxe", title:"Kirby: Triple Deluxe", date:"2014-05-02", score:80, scoreType:"critic", hltb:"6h", blurb:"Kirby joue sur la profondeur des deux plans grâce à la 3D."},
        {slug:"shovel-knight", title:"Shovel Knight", date:"2014-06-26", score:88, scoreType:"user", hltb:"6h", blurb:"Hommage parfait aux plateformers NES, à la pelle et au StreetPass."},
        {slug:"fantasy-life", title:"Fantasy Life", date:"2014-10-24", score:84, scoreType:"user", hltb:"40h", blurb:"RPG de vie de Level-5 où l'on enchaîne douze métiers avec bonheur."},
        {slug:"pokemon-omega-ruby-alpha-sapphire", title:"Pokémon Rubis Oméga / Saphir Alpha", date:"2014-11-21", score:84, scoreType:"user", hltb:"30h", blurb:"Hoenn refait en 3D, avec l'envol libre à dos de Pokémon."},
        {slug:"persona-q-shadow-of-the-labyrinth", title:"Persona Q: Shadow of the Labyrinth", date:"2014-11-25", score:80, scoreType:"critic", hltb:"60h", blurb:"Les castings de Persona 3 et 4 réunis dans un labyrinthe façon Etrian."},
        {slug:"zelda-majoras-mask-3d", title:"The Legend of Zelda: Majora's Mask 3D", date:"2015-02-13", score:89, scoreType:"user", hltb:"20h", blurb:"Les trois jours de Termina remasterisés, toujours aussi singuliers."},
        {slug:"monster-hunter-4-ultimate", title:"Monster Hunter 4 Ultimate", date:"2015-02-13", score:88, scoreType:"user", hltb:"60h", blurb:"La chasse gagne la verticalité et la monte, sommet de la série sur 3DS."},
        {slug:"code-name-steam", title:"Code Name: S.T.E.A.M.", date:"2015-03-13", score:72, scoreType:"critic", hltb:"30h", blurb:"Tactique à la vapeur d'Intelligent Systems, Lincoln contre les aliens."},
        {slug:"etrian-mystery-dungeon", title:"Etrian Mystery Dungeon", date:"2015-04-07", score:74, scoreType:"critic", hltb:"40h", blurb:"Les labyrinthes d'Etrian croisés au roguelike de Shiren."},
        {slug:"smt-devil-survivor-2-record-breaker", title:"Shin Megami Tensei: Devil Survivor 2 Record Breaker", date:"2015-05-05", score:81, scoreType:"critic", hltb:"40h", blurb:"Les Septentriones assiègent le Japon, version enrichie d'un épilogue complet."},
        {slug:"etrian-odyssey-2-untold", title:"Etrian Odyssey 2 Untold: The Fafnir Knight", date:"2015-08-04", score:80, scoreType:"critic", hltb:"40h", blurb:"Le deuxième labyrinthe refait avec mode histoire, version définitive."},
        {slug:"stella-glow", title:"Stella Glow", date:"2015-11-17", score:77, scoreType:"critic", hltb:"40h", blurb:"Tactical-RPG de sorcières chanteuses, chant du cygne d'Imageepoch."},
        {slug:"steamworld-heist", title:"SteamWorld Heist", date:"2015-12-10", score:87, scoreType:"critic", hltb:"15h", blurb:"Tactique au tour par tour où chaque tir se vise à la main, brillant."},
        {slug:"project-x-zone-2", title:"Project X Zone 2", date:"2016-02-16", score:71, scoreType:"critic", hltb:"40h", blurb:"Suite du crossover tactique, avec Nintendo invité à la fête."},
        {slug:"fire-emblem-fates", title:"Fire Emblem Fates", date:"2016-02-19", score:82, scoreType:"user", hltb:"30h", blurb:"Deux familles, deux voies : Héritage accessible ou Conquête exigeante."},
        {slug:"bravely-second-end-layer", title:"Bravely Second: End Layer", date:"2016-04-15", score:81, scoreType:"critic", hltb:"45h", blurb:"Suite directe de Bravely Default, système de jobs encore affiné."},
        {slug:"kirby-planet-robobot", title:"Kirby: Planet Robobot", date:"2016-06-10", score:87, scoreType:"user", hltb:"7h", blurb:"Kirby pilote une armure mécha, l'un des meilleurs épisodes de la série."},
        {slug:"7th-dragon-3-code-vfd", title:"7th Dragon III Code: VFD", date:"2016-07-12", score:76, scoreType:"critic", hltb:"30h", blurb:"Chasse aux dragons à travers les époques, seul épisode sorti en Occident."},
        {slug:"monster-hunter-generations", title:"Monster Hunter Generations", date:"2016-07-15", score:85, scoreType:"critic", hltb:"50h", blurb:"Épisode anniversaire aux styles de chasse libres, hommage à la saga."},
        {slug:"smt-4-apocalypse-3ds", title:"Shin Megami Tensei IV: Apocalypse", date:"2016-09-20", score:84, scoreType:"critic", hltb:"40h", blurb:"Relecture de SMT IV du point de vue d'un chasseur ressuscité."},
        {slug:"yo-kai-watch-2", title:"Yo-kai Watch 2", date:"2016-09-30", score:80, scoreType:"critic", hltb:"40h", blurb:"Guerre d'esprits entre deux versions, l'épisode le plus complet de la série."},
        {slug:"fire-emblem-echoes-shadows-of-valentia", title:"Fire Emblem Echoes: Shadows of Valentia", date:"2017-05-19", score:86, scoreType:"user", hltb:"30h", blurb:"Remake de Gaiden, doublé intégral et direction artistique superbe."},
        {slug:"ever-oasis", title:"Ever Oasis", date:"2017-06-23", score:77, scoreType:"critic", hltb:"25h", blurb:"Bâtir une oasis et explorer le désert, ultime charme signé Grezzo."},
        {slug:"monster-hunter-stories", title:"Monster Hunter Stories", date:"2017-09-08", score:81, scoreType:"critic", hltb:"35h", blurb:"Monster Hunter en RPG au tour par tour, monstres à élever."},
        {slug:"mario-and-luigi-superstar-saga-bowsers-minions", title:"Mario & Luigi: Superstar Saga + Les sbires de Bowser", date:"2017-10-06", score:81, scoreType:"critic", hltb:"15h", blurb:"Le premier Mario & Luigi refait, avec la campagne des sbires en bonus."},
        {slug:"pokemon-ultra-sun-ultra-moon", title:"Pokémon Ultra-Soleil / Ultra-Lune", date:"2017-11-17", score:84, scoreType:"critic", hltb:"35h", blurb:"Version définitive d'Alola, ultime épisode Pokémon de la 3DS."},
        {slug:"radiant-historia-perfect-chronology", title:"Radiant Historia: Perfect Chronology", date:"2018-02-13", score:83, scoreType:"critic", hltb:"35h", blurb:"Le RPG temporel dans sa version définitive, troisième ligne d'histoire incluse."},
        {slug:"the-alliance-alive", title:"The Alliance Alive", date:"2018-03-27", score:76, scoreType:"critic", hltb:"35h", blurb:"Hommage aux RPG SaGa, neuf héros sous un ciel confisqué."},
        {slug:"etrian-odyssey-nexus", title:"Etrian Odyssey Nexus", date:"2019-02-05", score:81, scoreType:"critic", hltb:"60h", blurb:"Le grand best-of des labyrinthes, adieu de la série à la 3DS."},
        {slug:"persona-q2-new-cinema-labyrinth", title:"Persona Q2: New Cinema Labyrinth", date:"2019-06-04", score:78, scoreType:"critic", hltb:"50h", blurb:"Les héros de Persona 3, 4 et 5 piégés dans un cinéma, adieu en beauté de la 3DS."}
      ]
    },

    gamecube: {
      key: "gamecube",
      name: "GameCube",
      short: "GC",
      color: "#4b3f8f",
      theme: "assets/theme-gamecube.css",
      page: "gamecube.html",
      ready: true,
      games: [
        {slug:"luigis-mansion", title:"Luigi's Mansion", date:"2001-11-18", score:85, scoreType:"user", hltb:"6h", blurb:"Luigi aspire les fantômes d'un manoir hanté, titre de lancement devenu culte."},
        {slug:"star-wars-rogue-squadron-2-rogue-leader", title:"Star Wars Rogue Squadron II: Rogue Leader", date:"2001-11-18", score:87, scoreType:"user", hltb:"6h", blurb:"Vitrine technique du lancement, batailles spatiales spectaculaires de la trilogie originale."},
        {slug:"pikmin", title:"Pikmin", date:"2001-12-02", score:88, scoreType:"user", hltb:"10h", blurb:"Stratégie en temps réel miniature signée Miyamoto, 30 jours pour repartir."},
        {slug:"sonic-adventure-2-battle", title:"Sonic Adventure 2: Battle", date:"2002-02-11", score:87, scoreType:"user", hltb:"11h", blurb:"Version enrichie de l'aventure Dreamcast, Chao Garden et mode 2 joueurs inclus."},
        {slug:"lost-kingdoms", title:"Lost Kingdoms", date:"2002-05-27", score:72, scoreType:"critic", hltb:"12h", blurb:"Action-RPG à cartes signé From Software, invocations en temps réel."},
        {slug:"star-fox-adventures", title:"Star Fox Adventures", date:"2002-09-23", score:82, scoreType:"critic", hltb:"15h", blurb:"Dernier jeu de Rare chez Nintendo, aventure à la Zelda avec Fox McCloud."},
        {slug:"robotech-battlecry", title:"Robotech: Battlecry", date:"2002-09-30", score:71, scoreType:"critic", hltb:"8h", blurb:"Les Veritech de Macross en action, hommage sincère à l'animé."},
        {slug:"timesplitters-2", title:"TimeSplitters 2", date:"2002-10-08", score:88, scoreType:"critic", hltb:"8h", blurb:"FPS à voyages temporels des créateurs de GoldenEye, campagne inventive."},
        {slug:"phantasy-star-online-episode-1-2", title:"Phantasy Star Online Episode I & II", date:"2002-10-29", score:85, scoreType:"critic", hltb:"30h", blurb:"Le RPG en ligne pionnier de Sega, jouable en écran partagé sur GameCube."},
        {slug:"medal-of-honor-frontline", title:"Medal of Honor: Frontline", date:"2002-11-07", score:82, scoreType:"critic", hltb:"8h", blurb:"Débarquement et lignes ennemies, la campagne la plus cinématographique de la série."},
        {slug:"baldurs-gate-dark-alliance", title:"Baldur's Gate: Dark Alliance", date:"2002-11-19", score:80, scoreType:"critic", hltb:"15h", blurb:"Action-RPG des Royaumes Oubliés, donjons et butin à deux sur le canapé."},
        {slug:"skies-of-arcadia-legends", title:"Skies of Arcadia Legends", date:"2003-01-27", score:89, scoreType:"user", hltb:"45h", blurb:"Portage enrichi du RPG de pirates du ciel de la Dreamcast."},
        {slug:"rayman-3-hoodlum-havoc", title:"Rayman 3: Hoodlum Havoc", date:"2003-03-21", score:76, scoreType:"critic", hltb:"10h", blurb:"Rayman contre les Hoodlums, plateforme haute en couleur et en verve."},
        {slug:"zelda-the-wind-waker", title:"The Legend of Zelda: The Wind Waker", date:"2003-03-24", score:90, scoreType:"user", hltb:"26h", blurb:"Navigation en cel-shading intemporel sur un océan sans fin."},
        {slug:"giftpia", title:"Giftpia", date:"2003-04-25", score:null, scoreType:"none", hltb:"20h", blurb:"Rembourser sa dette sur une île japonaise : l'aventure décalée de Skip, restée au Japon."},
        {slug:"lost-kingdoms-2", title:"Lost Kingdoms II", date:"2003-05-19", score:76, scoreType:"critic", hltb:"15h", blurb:"Suite plus riche et mieux rythmée, deck à composer soi-même."},
        {slug:"wario-world", title:"Wario World", date:"2003-06-23", score:71, scoreType:"critic", hltb:"5h", blurb:"Wario casse tout en 3D dans un écrin court mais généreux."},
        {slug:"the-simpsons-hit-and-run", title:"The Simpsons: Hit & Run", date:"2003-09-16", score:89, scoreType:"user", hltb:"12h", blurb:"GTA parodique dans Springfield, devenu culte auprès de toute une génération."},
        {slug:"freedom-fighters", title:"Freedom Fighters", date:"2003-09-26", score:81, scoreType:"critic", hltb:"8h", blurb:"Résistance urbaine contre l'occupant, escouade à commander d'un doigt."},
        {slug:"viewtiful-joe", title:"Viewtiful Joe", date:"2003-10-07", score:87, scoreType:"user", hltb:"7h", blurb:"Beat'em up stylisé de Capcom où Joe ralentit et accélère le temps."},
        {slug:"star-wars-rogue-squadron-3-rebel-strike", title:"Star Wars Rogue Squadron III: Rebel Strike", date:"2003-10-21", score:78, scoreType:"critic", hltb:"8h", blurb:"Rebel Strike conclut la trilogie Rogue Squadron, à pied comme en vol."},
        {slug:"gladius", title:"Gladius", date:"2003-10-28", score:78, scoreType:"critic", hltb:"30h", blurb:"Tournois de gladiateurs en tactique au tour par tour, signé LucasArts."},
        {slug:"i-ninja", title:"I-Ninja", date:"2003-11-11", score:72, scoreType:"critic", hltb:"10h", blurb:"Petit ninja colérique dans une action-plateforme nerveuse et inventive."},
        {slug:"sphinx-and-the-cursed-mummy", title:"Sphinx and the Cursed Mummy", date:"2003-11-11", score:76, scoreType:"critic", hltb:"15h", blurb:"Aventure égyptienne à la Zelda, entre héros solaire et momie maladroite."},
        {slug:"prince-of-persia-the-sands-of-time", title:"Prince of Persia: The Sands of Time", date:"2003-11-18", score:92, scoreType:"critic", hltb:"8h", blurb:"Renaissance acrobatique de la série, avec la dague qui remonte le temps."},
        {slug:"metal-arms-glitch-in-the-system", title:"Metal Arms: Glitch in the System", date:"2003-11-18", score:82, scoreType:"critic", hltb:"12h", blurb:"Robot rebelle et arsenal réjouissant, TPS culte passé sous les radars."},
        {slug:"beyond-good-and-evil", title:"Beyond Good & Evil", date:"2003-12-11", score:90, scoreType:"user", hltb:"10h", blurb:"Aventure de Michel Ancel portée par la reporter Jade, culte malgré son échec commercial."},
        {slug:"james-bond-everything-or-nothing", title:"James Bond 007: Everything or Nothing", date:"2004-02-17", score:82, scoreType:"critic", hltb:"6h", blurb:"007 en vue à la troisième personne, avec un casting hollywoodien complet."},
        {slug:"metal-gear-solid-the-twin-snakes", title:"Metal Gear Solid: The Twin Snakes", date:"2004-03-09", score:88, scoreType:"user", hltb:"12h", blurb:"Remake du premier Metal Gear Solid avec le gameplay de MGS2."},
        {slug:"pokemon-colosseum", title:"Pokémon Colosseum", date:"2004-03-22", score:84, scoreType:"user", hltb:"25h", blurb:"RPG Pokémon sur console de salon où l'on vole les Pokémon Obscurs."},
        {slug:"custom-robo", title:"Custom Robo", date:"2004-05-11", score:71, scoreType:"critic", hltb:"20h", blurb:"RPG où l'on assemble son robot pièce par pièce, récit étonnamment sombre."},
        {slug:"zelda-four-swords-adventures", title:"The Legend of Zelda: Four Swords Adventures", date:"2004-06-07", score:86, scoreType:"critic", hltb:"15h", blurb:"Zelda coopératif à quatre Link, connecté aux Game Boy Advance."},
        {slug:"spider-man-2", title:"Spider-Man 2", date:"2004-06-28", score:80, scoreType:"critic", hltb:"10h", blurb:"La balancée dans New York qui a défini les jeux de super-héros."},
        {slug:"tales-of-symphonia", title:"Tales of Symphonia", date:"2004-07-13", score:89, scoreType:"user", hltb:"45h", blurb:"RPG d'action au scénario généreux, épisode le plus aimé de la série Tales."},
        {slug:"pikmin-2", title:"Pikmin 2", date:"2004-08-30", score:90, scoreType:"user", hltb:"20h", blurb:"Suite sans limite de temps, grottes, trésors et deux capitaines."},
        {slug:"x-men-legends", title:"X-Men Legends", date:"2004-09-21", score:82, scoreType:"critic", hltb:"15h", blurb:"Action-RPG coopératif à quatre, les mutants enfin en équipe."},
        {slug:"second-sight", title:"Second Sight", date:"2004-09-21", score:75, scoreType:"critic", hltb:"8h", blurb:"Pouvoirs psychiques et infiltration dans un thriller à double époque."},
        {slug:"paper-mario-the-thousand-year-door", title:"Paper Mario: The Thousand-Year Door", date:"2004-10-11", score:91, scoreType:"user", hltb:"35h", blurb:"RPG en papier à l'écriture hilarante, souvent cité comme le meilleur Paper Mario."},
        {slug:"baten-kaitos-eternal-wings", title:"Baten Kaitos: Eternal Wings and the Lost Ocean", date:"2004-11-16", score:80, scoreType:"critic", hltb:"55h", blurb:"RPG à cartes aux décors peints à la main, dans un monde d'îles célestes."},
        {slug:"viewtiful-joe-2", title:"Viewtiful Joe 2", date:"2004-11-18", score:86, scoreType:"critic", hltb:"8h", blurb:"Suite directe avec Silvia jouable et un nouveau pouvoir de zoom."},
        {slug:"timesplitters-future-perfect", title:"TimeSplitters: Future Perfect", date:"2005-03-21", score:84, scoreType:"critic", hltb:"8h", blurb:"Voyages temporels et humour absurde, le FPS fun par excellence."},
        {slug:"splinter-cell-chaos-theory", title:"Splinter Cell: Chaos Theory", date:"2005-03-31", score:87, scoreType:"critic", hltb:"12h", blurb:"L'infiltration à son sommet, lumière et son comme armes."},
        {slug:"killer7", title:"Killer7", date:"2005-07-07", score:84, scoreType:"user", hltb:"15h", blurb:"Thriller stylisé et radical de Suda51, sept tueurs dans un même corps."},
        {slug:"battalion-wars", title:"Battalion Wars", date:"2005-09-19", score:76, scoreType:"critic", hltb:"12h", blurb:"Advance Wars passe à l'action en temps réel, escouades en pagaille."},
        {slug:"pokemon-xd-gale-of-darkness", title:"Pokémon XD: Gale of Darkness", date:"2005-10-03", score:80, scoreType:"user", hltb:"30h", blurb:"Suite de Colosseum autour d'un Lugia Obscur réputé impossible à purifier."},
        {slug:"fire-emblem-path-of-radiance", title:"Fire Emblem: Path of Radiance", date:"2005-10-17", score:90, scoreType:"user", hltb:"30h", blurb:"Premier Fire Emblem en 3D, début de l'histoire d'Ike et des mercenaires de Greil."},
        {slug:"gun", title:"Gun", date:"2005-11-08", score:76, scoreType:"critic", hltb:"8h", blurb:"Western en monde ouvert, vengeance sanglante sur la piste de l'Ouest."},
        {slug:"chibi-robo", title:"Chibi-Robo!", date:"2006-02-06", score:77, scoreType:"critic", hltb:"14h", blurb:"Petit robot ménager qui répare le quotidien d'une famille, attachant et original."},
        {slug:"baten-kaitos-origins", title:"Baten Kaitos Origins", date:"2006-09-25", score:84, scoreType:"critic", hltb:"40h", blurb:"Préquelle au système de cartes affiné, jamais sortie en Europe."},
        {slug:"zelda-twilight-princess", title:"The Legend of Zelda: Twilight Princess", date:"2006-12-11", score:90, scoreType:"user", hltb:"34h", blurb:"Ultime jeu GameCube, Link loup et crépuscule pour un adieu épique."}
      ]
    },

    ps2: {
      key: "ps2",
      name: "PlayStation 2",
      short: "PS2",
      color: "#4a5fc1",
      theme: "assets/theme-ps2.css",
      page: "ps2.html",
      ready: true,
      games: [
        {slug:"onimusha-warlords", title:"Onimusha: Warlords", date:"2001-03-13", score:86, scoreType:"critic", hltb:"6h", blurb:"Samouraïs contre démons dans un Japon féodal réinventé par Capcom."},
        {slug:"dark-cloud", title:"Dark Cloud", date:"2001-05-29", score:80, scoreType:"critic", hltb:"25h", blurb:"Donjons et reconstruction de villages, premier RPG maison de Level-5."},
        {slug:"klonoa-2-lunateas-veil", title:"Klonoa 2: Lunatea's Veil", date:"2001-07-24", score:91, scoreType:"critic", hltb:"8h", blurb:"Plateforme 2.5D onirique et mélancolique, injustement méconnue."},
        {slug:"ico", title:"Ico", date:"2001-09-24", score:90, scoreType:"user", hltb:"6h", blurb:"Un garçon, une princesse et un château : la poésie selon Fumito Ueda."},
        {slug:"devil-may-cry", title:"Devil May Cry", date:"2001-10-16", score:88, scoreType:"user", hltb:"8h", blurb:"Dante invente le jeu d'action stylé, pistolets et épée démoniaque en main."},
        {slug:"grand-theft-auto-3", title:"Grand Theft Auto III", date:"2001-10-22", score:87, scoreType:"user", hltb:"16h", blurb:"Liberty City en monde ouvert 3D, le jeu qui a tout changé."},
        {slug:"ace-combat-04-shattered-skies", title:"Ace Combat 04: Shattered Skies", date:"2001-11-01", score:89, scoreType:"critic", hltb:"10h", blurb:"Guerre aérienne et récit poignant vu du sol, l'envol de la série."},
        {slug:"metal-gear-solid-2-sons-of-liberty", title:"Metal Gear Solid 2: Sons of Liberty", date:"2001-11-13", score:89, scoreType:"user", hltb:"11h", blurb:"Infiltration virtuose et scénario vertigineux signés Hideo Kojima."},
        {slug:"jak-and-daxter-the-precursor-legacy", title:"Jak and Daxter: The Precursor Legacy", date:"2001-12-03", score:87, scoreType:"user", hltb:"10h", blurb:"Plateforme sans temps de chargement de Naughty Dog, monde continu."},
        {slug:"shadow-hearts", title:"Shadow Hearts", date:"2001-12-11", score:73, scoreType:"critic", hltb:"35h", blurb:"RPG occulte dans l'Eurasie de 1913, avec sa fameuse Judgment Ring."},
        {slug:"kingdom-hearts", title:"Kingdom Hearts", date:"2002-09-16", score:88, scoreType:"user", hltb:"30h", blurb:"La rencontre improbable de Disney et Square, devenue légendaire."},
        {slug:"sly-cooper-and-the-thievius-raccoonus", title:"Sly Cooper and the Thievius Raccoonus", date:"2002-09-23", score:86, scoreType:"critic", hltb:"7h", blurb:"Cambriolages en cel-shading avec le raton laveur le plus classe du genre."},
        {slug:"wild-arms-3", title:"Wild Arms 3", date:"2002-10-15", score:79, scoreType:"critic", hltb:"35h", blurb:"Western fantastique en cel-shading, chevauchées et gardiens anciens."},
        {slug:"suikoden-3", title:"Suikoden III", date:"2002-10-24", score:81, scoreType:"critic", hltb:"35h", blurb:"Trois points de vue croisés et 108 étoiles du destin à recruter."},
        {slug:"gta-vice-city", title:"Grand Theft Auto: Vice City", date:"2002-10-27", score:87, scoreType:"user", hltb:"18h", blurb:"Miami années 80, néons et radio culte : le GTA le plus stylé."},
        {slug:"ratchet-and-clank", title:"Ratchet & Clank", date:"2002-11-04", score:89, scoreType:"user", hltb:"11h", blurb:"Duo lombax-robot et arsenal délirant, début d'une grande série."},
        {slug:"dark-cloud-2", title:"Dark Cloud 2", date:"2003-02-17", score:87, scoreType:"critic", hltb:"45h", blurb:"Action-RPG de Level-5 mêlant donjons, photos, inventions et reconstruction."},
        {slug:"xenosaga-episode-1", title:"Xenosaga Episode I", date:"2003-02-25", score:83, scoreType:"critic", hltb:"40h", blurb:"Space opera philosophique très narratif, début de la trilogie de Monolith."},
        {slug:"zone-of-the-enders-the-2nd-runner", title:"Zone of the Enders: The 2nd Runner", date:"2003-03-11", score:84, scoreType:"critic", hltb:"6h", blurb:"Combats de mechas fulgurants produits par Kojima, pur concentré d'adrénaline."},
        {slug:"disgaea-hour-of-darkness", title:"Disgaea: Hour of Darkness", date:"2003-08-27", score:89, scoreType:"user", hltb:"45h", blurb:"Tactical-RPG parodique aux niveaux 9999 et à l'humour démoniaque."},
        {slug:"jak-2", title:"Jak II", date:"2003-10-14", score:87, scoreType:"critic", hltb:"15h", blurb:"Virage sombre et monde ouvert pour la suite de Naughty Dog."},
        {slug:"ratchet-and-clank-going-commando", title:"Ratchet & Clank: Going Commando", date:"2003-11-11", score:90, scoreType:"user", hltb:"15h", blurb:"Suite plus grande et mieux armée, la formule Ratchet à maturité."},
        {slug:"star-ocean-till-the-end-of-time", title:"Star Ocean: Till the End of Time", date:"2004-08-31", score:80, scoreType:"critic", hltb:"40h", blurb:"Science-fantasy aux combats en temps réel, avec un twist resté fameux."},
        {slug:"sly-2-band-of-thieves", title:"Sly 2: Band of Thieves", date:"2004-09-14", score:88, scoreType:"critic", hltb:"14h", blurb:"Braquages en équipe et ville ouverte, le meilleur épisode de la bande."},
        {slug:"shadow-hearts-covenant", title:"Shadow Hearts: Covenant", date:"2004-09-27", score:85, scoreType:"critic", hltb:"40h", blurb:"RPG gothique dans l'Europe de 1915, sommet de la série."},
        {slug:"shin-megami-tensei-nocturne", title:"Shin Megami Tensei: Nocturne", date:"2004-10-12", score:90, scoreType:"user", hltb:"50h", blurb:"Tokyo détruit et renaissance du monde, le SMT le plus culte."},
        {slug:"ace-combat-5-the-unsung-war", title:"Ace Combat 5: The Unsung War", date:"2004-10-25", score:84, scoreType:"critic", hltb:"12h", blurb:"Dogfights spectaculaires et escadron attachant, l'apogée de la série."},
        {slug:"gta-san-andreas", title:"Grand Theft Auto: San Andreas", date:"2004-10-26", score:90, scoreType:"user", hltb:"31h", blurb:"Trois villes, un État entier : le GTA le plus vaste et le plus aimé."},
        {slug:"ratchet-and-clank-up-your-arsenal", title:"Ratchet & Clank: Up Your Arsenal", date:"2004-11-02", score:91, scoreType:"critic", hltb:"12h", blurb:"Troisième épisode surarmé, avec le Dr Nefarious à la barre."},
        {slug:"jak-3", title:"Jak 3", date:"2004-11-09", score:84, scoreType:"critic", hltb:"12h", blurb:"Conclusion de la trilogie entre désert et ville, buggies à l'appui."},
        {slug:"metal-gear-solid-3-snake-eater", title:"Metal Gear Solid 3: Snake Eater", date:"2004-11-17", score:93, scoreType:"user", hltb:"16h", blurb:"Survie en jungle pendant la guerre froide, souvent cité comme le meilleur MGS."},
        {slug:"devil-may-cry-3-dantes-awakening", title:"Devil May Cry 3: Dante's Awakening", date:"2005-03-01", score:89, scoreType:"user", hltb:"12h", blurb:"Dante jeune et arrogant, action au style exigeant et jubilatoire."},
        {slug:"god-of-war", title:"God of War", date:"2005-03-22", score:91, scoreType:"user", hltb:"9h", blurb:"La vengeance de Kratos contre l'Olympe, brutale et mise en scène."},
        {slug:"digital-devil-saga-ps2", title:"Shin Megami Tensei: Digital Devil Saga", date:"2005-04-05", score:84, scoreType:"critic", hltb:"30h", blurb:"Spin-off SMT au tour par tour où les héros dévorent leurs ennemis."},
        {slug:"psychonauts", title:"Psychonauts", date:"2005-06-21", score:88, scoreType:"user", hltb:"14h", blurb:"Raz explore l'esprit des gens dans l'aventure la plus inventive de Tim Schafer."},
        {slug:"the-warriors", title:"The Warriors", date:"2005-10-17", score:84, scoreType:"critic", hltb:"15h", blurb:"Rockstar adapte le film culte en beat'em up urbain étonnamment riche."},
        {slug:"shadow-of-the-colossus", title:"Shadow of the Colossus", date:"2005-10-18", score:92, scoreType:"user", hltb:"8h", blurb:"Seize colosses dans une terre interdite, chef-d'oeuvre de Fumito Ueda."},
        {slug:"prince-of-persia-the-two-thrones", title:"Prince of Persia: The Two Thrones", date:"2005-12-01", score:85, scoreType:"critic", hltb:"8h", blurb:"Le prince aux deux visages referme la trilogie des sables."},
        {slug:"kingdom-hearts-2", title:"Kingdom Hearts II", date:"2006-03-28", score:89, scoreType:"user", hltb:"35h", blurb:"Sora revient dans une aventure plus ample au système de combat affiné."},
        {slug:"yakuza", title:"Yakuza", date:"2006-09-05", score:75, scoreType:"critic", hltb:"20h", blurb:"Kiryu protège une orpheline dans Kamurocho, naissance d'une saga culte."},
        {slug:"okami", title:"Ōkami", date:"2006-09-19", score:91, scoreType:"user", hltb:"30h", blurb:"La déesse Amaterasu repeint le monde au pinceau céleste, estampe jouable."},
        {slug:"valkyrie-profile-2-silmeria", title:"Valkyrie Profile 2: Silmeria", date:"2006-09-26", score:84, scoreType:"critic", hltb:"40h", blurb:"Silmeria et ses einherjar dans un système de combat d'orfèvre."},
        {slug:"god-hand", title:"God Hand", date:"2006-10-10", score:89, scoreType:"user", hltb:"12h", blurb:"Beat'em up délirant et ultra-exigeant de Clover, devenu culte."},
        {slug:"bully", title:"Bully", date:"2006-10-17", score:86, scoreType:"user", hltb:"17h", blurb:"Rockstar au pensionnat : chahut, cours et petites magouilles."},
        {slug:"rogue-galaxy", title:"Rogue Galaxy", date:"2007-01-30", score:82, scoreType:"critic", hltb:"45h", blurb:"Space opera d'action-RPG de Level-5, pirates et planètes exotiques."},
        {slug:"god-of-war-2", title:"God of War II", date:"2007-03-13", score:91, scoreType:"user", hltb:"11h", blurb:"Kratos défie les Titans, chant du cygne spectaculaire de la console."},
        {slug:"odin-sphere", title:"Odin Sphere", date:"2007-05-22", score:83, scoreType:"critic", hltb:"25h", blurb:"Cinq destins croisés en 2D somptueuse signée Vanillaware."},
        {slug:"super-robot-taisen-original-generations", title:"Super Robot Taisen: Original Generations", date:"2007-06-28", score:null, scoreType:"none", hltb:"60h", blurb:"Les deux épisodes GBA refaits en grand, sommet mecha resté au Japon."},
        {slug:"persona-3-fes", title:"Persona 3 FES", date:"2008-04-22", score:90, scoreType:"user", hltb:"70h", blurb:"Lycée le jour, Tartare la nuit : version enrichie du RPG qui a réinventé Persona."},
        {slug:"persona-4", title:"Persona 4", date:"2008-12-09", score:92, scoreType:"user", hltb:"70h", blurb:"Enquête surnaturelle à Inaba, ultime grand RPG de la PlayStation 2."}
      ]
    },

    jrpg: {
      key: "jrpg",
      name: "JRPG",
      short: "JRPG",
      color: "#c14a6b",
      theme: "assets/theme-jrpg.css",
      page: "jrpg.html",
      ready: true,
      games: [
        {slug:"dark-cloud", title:"Dark Cloud (PS2)", date:"2001-05-29", score:80, scoreType:"critic", hltb:"25h", blurb:"Donjons et reconstruction de villages, premier RPG maison de Level-5."},
        {slug:"shadow-hearts", title:"Shadow Hearts (PS2)", date:"2001-12-11", score:73, scoreType:"critic", hltb:"35h", blurb:"RPG occulte dans l'Eurasie de 1913, avec sa fameuse Judgment Ring."},
        {slug:"kingdom-hearts", title:"Kingdom Hearts (PS2)", date:"2002-09-16", score:88, scoreType:"user", hltb:"30h", blurb:"La rencontre improbable de Disney et Square, devenue légendaire."},
        {slug:"wild-arms-3", title:"Wild Arms 3 (PS2)", date:"2002-10-15", score:79, scoreType:"critic", hltb:"35h", blurb:"Western fantastique en cel-shading, chevauchées et gardiens anciens."},
        {slug:"suikoden-3", title:"Suikoden III (PS2)", date:"2002-10-24", score:81, scoreType:"critic", hltb:"35h", blurb:"Trois points de vue croisés et 108 étoiles du destin à recruter."},
        {slug:"skies-of-arcadia-legends", title:"Skies of Arcadia Legends (GC)", date:"2003-01-27", score:89, scoreType:"user", hltb:"45h", blurb:"Portage enrichi du RPG de pirates du ciel de la Dreamcast."},
        {slug:"breath-of-fire-dragon-quarter", title:"Breath of Fire: Dragon Quarter (PS2)", date:"2003-02-14", score:78, scoreType:"critic", hltb:"20h", blurb:"Épisode radical en sous-sol, compteur dragon et recommencements assumés."},
        {slug:"dark-cloud-2", title:"Dark Cloud 2 (PS2)", date:"2003-02-17", score:87, scoreType:"critic", hltb:"45h", blurb:"Action-RPG mêlant donjons, photos, inventions et reconstruction."},
        {slug:"xenosaga-episode-1", title:"Xenosaga Episode I (PS2)", date:"2003-02-25", score:83, scoreType:"critic", hltb:"40h", blurb:"Space opera philosophique très narratif, début de la trilogie de Monolith."},
        {slug:"disgaea-hour-of-darkness", title:"Disgaea: Hour of Darkness (PS2)", date:"2003-08-27", score:89, scoreType:"user", hltb:"45h", blurb:"Tactical-RPG parodique aux niveaux 9999 et à l'humour démoniaque."},
        {slug:"pokemon-colosseum", title:"Pokémon Colosseum (GC)", date:"2004-03-22", score:84, scoreType:"user", hltb:"25h", blurb:"RPG Pokémon de salon où l'on vole les Pokémon Obscurs."},
        {slug:"front-mission-4", title:"Front Mission 4 (PS2)", date:"2004-06-15", score:77, scoreType:"critic", hltb:"40h", blurb:"Tactique de wanzers entre Europe et Venezuela, mechas et complots."},
        {slug:"tales-of-symphonia", title:"Tales of Symphonia (GC)", date:"2004-07-13", score:89, scoreType:"user", hltb:"45h", blurb:"RPG d'action au scénario généreux, épisode le plus aimé des Tales."},
        {slug:"star-ocean-till-the-end-of-time", title:"Star Ocean: Till the End of Time (PS2)", date:"2004-08-31", score:80, scoreType:"critic", hltb:"40h", blurb:"Science-fantasy aux combats en temps réel, avec un twist resté fameux."},
        {slug:"shadow-hearts-covenant", title:"Shadow Hearts: Covenant (PS2)", date:"2004-09-27", score:85, scoreType:"critic", hltb:"40h", blurb:"RPG gothique dans l'Europe de 1915, sommet de la série."},
        {slug:"paper-mario-the-thousand-year-door", title:"Paper Mario: The Thousand-Year Door (GC)", date:"2004-10-11", score:91, scoreType:"user", hltb:"35h", blurb:"RPG en papier à l'écriture hilarante, souvent cité comme le meilleur Paper Mario."},
        {slug:"shin-megami-tensei-nocturne", title:"Shin Megami Tensei: Nocturne (PS2)", date:"2004-10-12", score:90, scoreType:"user", hltb:"50h", blurb:"Tokyo détruit et renaissance du monde, le SMT le plus culte."},
        {slug:"baten-kaitos-eternal-wings", title:"Baten Kaitos: Eternal Wings and the Lost Ocean (GC)", date:"2004-11-16", score:80, scoreType:"critic", hltb:"55h", blurb:"RPG à cartes aux décors peints à la main, dans un monde d'îles célestes."},
        {slug:"digital-devil-saga", title:"Shin Megami Tensei: Digital Devil Saga (PS2)", date:"2005-04-05", score:84, scoreType:"critic", hltb:"30h", blurb:"Spin-off SMT au tour par tour où les héros dévorent leurs ennemis."},
        {slug:"radiata-stories", title:"Radiata Stories (PS2)", date:"2005-09-06", score:77, scoreType:"critic", hltb:"40h", blurb:"RPG léger aux 177 personnages recrutables et au choix déchirant."},
        {slug:"pokemon-xd-gale-of-darkness", title:"Pokémon XD: Gale of Darkness (GC)", date:"2005-10-03", score:80, scoreType:"user", hltb:"30h", blurb:"Suite de Colosseum autour d'un Lugia Obscur réputé impossible à purifier."},
        {slug:"digital-devil-saga-2", title:"Shin Megami Tensei: Digital Devil Saga 2 (PS2)", date:"2005-10-04", score:84, scoreType:"critic", hltb:"30h", blurb:"Conclusion du diptyque, du Junkyard vers le monde réel."},
        {slug:"fire-emblem-path-of-radiance", title:"Fire Emblem: Path of Radiance (GC)", date:"2005-10-17", score:90, scoreType:"user", hltb:"30h", blurb:"Premier Fire Emblem en 3D, début de l'histoire d'Ike et des mercenaires de Greil."},
        {slug:"suikoden-5", title:"Suikoden V (PS2)", date:"2006-03-21", score:78, scoreType:"critic", hltb:"45h", blurb:"Retour aux sources pour la saga des 108 étoiles du destin."},
        {slug:"kingdom-hearts-2", title:"Kingdom Hearts II (PS2)", date:"2006-03-28", score:89, scoreType:"user", hltb:"35h", blurb:"Sora revient dans une aventure plus ample au système de combat affiné."},
        {slug:"disgaea-2", title:"Disgaea 2: Cursed Memories (PS2)", date:"2006-08-29", score:84, scoreType:"critic", hltb:"45h", blurb:"Nouvelle plongée dans le Netherworld, toujours plus de niveaux absurdes."},
        {slug:"xenosaga-episode-3", title:"Xenosaga Episode III (PS2)", date:"2006-08-29", score:81, scoreType:"critic", hltb:"35h", blurb:"Conclusion resserrée et spectaculaire de la trilogie KOS-MOS."},
        {slug:"baten-kaitos-origins", title:"Baten Kaitos Origins (GC)", date:"2006-09-25", score:84, scoreType:"critic", hltb:"40h", blurb:"Préquelle au système de cartes affiné, jamais sortie en Europe."},
        {slug:"valkyrie-profile-2-silmeria", title:"Valkyrie Profile 2: Silmeria (PS2)", date:"2006-09-26", score:84, scoreType:"critic", hltb:"40h", blurb:"Silmeria et ses einherjar dans un système de combat d'orfèvre."},
        {slug:"tales-of-the-abyss", title:"Tales of the Abyss (PS2)", date:"2006-10-10", score:78, scoreType:"critic", hltb:"45h", blurb:"Luke apprend à exister au-delà de sa réplique, un Tales majeur."},
        {slug:"rogue-galaxy", title:"Rogue Galaxy (PS2)", date:"2007-01-30", score:82, scoreType:"critic", hltb:"45h", blurb:"Space opera d'action-RPG de Level-5, pirates et planètes exotiques."},
        {slug:"odin-sphere", title:"Odin Sphere (PS2)", date:"2007-05-22", score:83, scoreType:"critic", hltb:"25h", blurb:"Cinq destins croisés en 2D somptueuse signée Vanillaware."},
        {slug:"super-robot-taisen-original-generations", title:"Super Robot Taisen: Original Generations (PS2)", date:"2007-06-28", score:null, scoreType:"none", hltb:"60h", blurb:"Les deux épisodes GBA refaits en grand, sommet mecha resté au Japon."},
        {slug:"fire-emblem-radiant-dawn", title:"Fire Emblem: Radiant Dawn (Wii)", date:"2007-11-05", score:78, scoreType:"critic", hltb:"35h", blurb:"Suite directe de Path of Radiance, exigeante et riche en points de vue."},
        {slug:"soma-bringer", title:"Soma Bringer (DS)", date:"2008-02-28", score:null, scoreType:"none", hltb:"25h", blurb:"L'action-RPG de Monolith Soft resté au Japon, pensé pour le jeu à trois."},
        {slug:"the-world-ends-with-you", title:"The World Ends with You (DS)", date:"2008-04-22", score:90, scoreType:"user", hltb:"20h", blurb:"RPG d'action ultra-stylé dans Shibuya, combats sur les deux écrans."},
        {slug:"persona-3-fes", title:"Persona 3 FES (PS2)", date:"2008-04-22", score:90, scoreType:"user", hltb:"70h", blurb:"Lycée le jour, Tartare la nuit : le RPG qui a réinventé Persona."},
        {slug:"eternal-sonata", title:"Eternal Sonata (PS3)", date:"2008-10-21", score:80, scoreType:"critic", hltb:"30h", blurb:"RPG musical rêvé par Chopin mourant, mélancolique et coloré."},
        {slug:"valkyria-chronicles", title:"Valkyria Chronicles (PS3)", date:"2008-11-04", score:89, scoreType:"user", hltb:"30h", blurb:"Tactique en aquarelle dans une Europe alternative en guerre."},
        {slug:"chrono-trigger", title:"Chrono Trigger (DS)", date:"2008-11-25", score:91, scoreType:"user", hltb:"23h", blurb:"Le voyage temporel légendaire de la SNES, enfin portable."},
        {slug:"persona-4", title:"Persona 4 (PS2)", date:"2008-12-09", score:92, scoreType:"user", hltb:"70h", blurb:"Enquête surnaturelle à Inaba, ultime grand RPG de la PlayStation 2."},
        {slug:"fire-emblem-shadow-dragon", title:"Fire Emblem: Shadow Dragon (DS)", date:"2009-02-16", score:81, scoreType:"critic", hltb:"20h", blurb:"Remake du tout premier Fire Emblem, avec Marth."},
        {slug:"suikoden-tierkreis", title:"Suikoden Tierkreis (DS)", date:"2009-03-17", score:78, scoreType:"critic", hltb:"30h", blurb:"Les 108 étoiles en poche, dans un multivers inédit."},
        {slug:"pokemon-platinum", title:"Pokémon Platine (DS)", date:"2009-03-22", score:88, scoreType:"user", hltb:"40h", blurb:"Version définitive de Sinnoh, avec le Monde Distorsion."},
        {slug:"knights-in-the-nightmare", title:"Knights in the Nightmare (DS)", date:"2009-06-02", score:80, scoreType:"critic", hltb:"25h", blurb:"Hybride de SRPG et de shoot'em up signé Sting, unique en son genre."},
        {slug:"muramasa-the-demon-blade", title:"Muramasa: The Demon Blade (Wii)", date:"2009-09-08", score:81, scoreType:"critic", hltb:"15h", blurb:"Sabres maudits et estampes animées, Vanillaware au sommet sur Wii."},
        {slug:"mario-and-luigi-bowsers-inside-story", title:"Mario & Luigi: Voyage au centre de Bowser (DS)", date:"2009-09-14", score:89, scoreType:"user", hltb:"25h", blurb:"Mario et Luigi explorent l'intérieur de Bowser, sommet de la série."},
        {slug:"demons-souls", title:"Demon's Souls (PS3)", date:"2009-10-06", score:92, scoreType:"user", hltb:"30h", blurb:"L'acte fondateur de From Software, Boletaria et ses âmes."},
        {slug:"pokemon-mystery-dungeon-explorers-of-sky", title:"Pokémon Donjon Mystère: Explorateurs du Ciel (DS)", date:"2009-10-12", score:86, scoreType:"user", hltb:"35h", blurb:"Version ultime d'Explorateurs, l'histoire Pokémon la plus émouvante."},
        {slug:"pokemon-heartgold-soulsilver", title:"Pokémon HeartGold / SoulSilver (DS)", date:"2010-03-14", score:90, scoreType:"user", hltb:"40h", blurb:"Remake de la deuxième génération, Johto et Kanto réunis."},
        {slug:"infinite-space", title:"Infinite Space (DS)", date:"2010-03-16", score:78, scoreType:"critic", hltb:"60h", blurb:"Space opera tentaculaire de PlatinumGames, flottes à composer et récit fleuve."},
        {slug:"resonance-of-fate", title:"Resonance of Fate (PS3)", date:"2010-03-16", score:80, scoreType:"user", hltb:"40h", blurb:"Ballet aérien d'armes à feu signé tri-Ace, culte et singulier."},
        {slug:"smt-strange-journey", title:"Shin Megami Tensei: Strange Journey (DS)", date:"2010-03-23", score:80, scoreType:"critic", hltb:"40h", blurb:"Expédition SMT pure et dure en Antarctique, sombre et fascinante."},
        {slug:"sakura-wars-so-long-my-love", title:"Sakura Wars: So Long, My Love (PS2)", date:"2010-03-30", score:78, scoreType:"critic", hltb:"25h", blurb:"Théâtre, mechas à vapeur et romance à New York, ultime éclat PS2."},
        {slug:"nier", title:"Nier (PS3)", date:"2010-04-27", score:88, scoreType:"user", hltb:"20h", blurb:"Récit déchirant et musiques inoubliables, culte malgré ses rugosités."},
        {slug:"lufia-curse-of-the-sinistrals", title:"Lufia: Curse of the Sinistrals (DS)", date:"2010-08-31", score:77, scoreType:"critic", hltb:"25h", blurb:"Remake en action-RPG du classique SNES, rythmé et généreux."},
        {slug:"rune-factory-3", title:"Rune Factory 3 (DS)", date:"2010-11-09", score:80, scoreType:"critic", hltb:"50h", blurb:"Donjons, ferme et romance : l'épisode DS le plus abouti de la série."},
        {slug:"golden-sun-dark-dawn", title:"Golden Sun: Dark Dawn (DS)", date:"2010-11-29", score:79, scoreType:"critic", hltb:"30h", blurb:"La saga Psynergie revient une génération plus tard."},
        {slug:"pokemon-black-white", title:"Pokémon Noir / Blanc (DS)", date:"2011-03-06", score:82, scoreType:"user", hltb:"32h", blurb:"Cinquième génération à Unys, avec uniquement de nouveaux Pokémon."},
        {slug:"smt-devil-survivor-overclocked", title:"Shin Megami Tensei: Devil Survivor Overclocked (3DS)", date:"2011-08-23", score:78, scoreType:"critic", hltb:"30h", blurb:"Tokyo bouclé pendant sept jours, version définitive avec huitième jour."},
        {slug:"disgaea-4", title:"Disgaea 4: A Promise Unforgotten (PS3)", date:"2011-09-06", score:80, scoreType:"critic", hltb:"45h", blurb:"Sardines, révolution et grinding infini dans le Netherworld en HD."},
        {slug:"solatorobo-red-the-hunter", title:"Solatorobo: Red the Hunter (DS)", date:"2011-09-27", score:77, scoreType:"critic", hltb:"15h", blurb:"Chasseur canin et mécha dans un archipel céleste, dix ans de fabrication."},
        {slug:"dark-souls", title:"Dark Souls (PS3)", date:"2011-10-04", score:90, scoreType:"user", hltb:"40h", blurb:"Lordran interconnecté et implacable, le RPG d'action qui a fait école."},
        {slug:"tales-of-graces-f", title:"Tales of Graces f (PS3)", date:"2012-03-13", score:77, scoreType:"critic", hltb:"40h", blurb:"Le système de combat le plus affûté de la série Tales."},
        {slug:"inazuma-eleven-2", title:"Inazuma Eleven 2 (DS)", date:"2012-05-18", score:79, scoreType:"critic", hltb:"35h", blurb:"RPG de football contre des envahisseurs, deux versions au choix."},
        {slug:"pokemon-conquest", title:"Pokémon Conquest (DS)", date:"2012-06-18", score:80, scoreType:"critic", hltb:"30h", blurb:"Pokémon rencontre Nobunaga's Ambition, crossover tactique inattendu."},
        {slug:"the-last-story", title:"The Last Story (Wii)", date:"2012-08-14", score:80, scoreType:"critic", hltb:"20h", blurb:"Le RPG crépusculaire de Sakaguchi sur Wii, intime et resserré."},
        {slug:"pokemon-black-2-white-2", title:"Pokémon Noir 2 / Blanc 2 (DS)", date:"2012-10-07", score:84, scoreType:"user", hltb:"35h", blurb:"Suites directes inédites, retour à Unys deux ans après."},
        {slug:"ni-no-kuni-wrath-of-the-white-witch", title:"Ni no Kuni: Wrath of the White Witch (PS3)", date:"2013-01-22", score:85, scoreType:"user", hltb:"45h", blurb:"Conte animé par le studio Ghibli, féérique et généreux."},
        {slug:"fire-emblem-awakening", title:"Fire Emblem: Awakening (3DS)", date:"2013-02-04", score:89, scoreType:"user", hltb:"25h", blurb:"L'épisode qui a sauvé la série, avec mariages et enfants entre unités."},
        {slug:"etrian-odyssey-4", title:"Etrian Odyssey IV: Legends of the Titan (3DS)", date:"2013-02-26", score:82, scoreType:"critic", hltb:"40h", blurb:"Dungeon-RPG où l'on dessine soi-même sa carte sur l'écran tactile."},
        {slug:"dragons-dogma-dark-arisen", title:"Dragon's Dogma: Dark Arisen (PS3)", date:"2013-04-23", score:87, scoreType:"critic", hltb:"45h", blurb:"Chasse aux chimères et système de pions, l'action-RPG culte de Capcom."},
        {slug:"shin-megami-tensei-4", title:"Shin Megami Tensei IV (3DS)", date:"2013-07-16", score:83, scoreType:"critic", hltb:"45h", blurb:"Apocalypse démoniaque entre royaume médiéval et Tokyo en ruines."},
        {slug:"tales-of-xillia", title:"Tales of Xillia (PS3)", date:"2013-08-06", score:78, scoreType:"critic", hltb:"40h", blurb:"Deux héros au choix pour l'épisode anniversaire des Tales."},
        {slug:"mario-and-luigi-dream-team", title:"Mario & Luigi: Dream Team (3DS)", date:"2013-08-11", score:81, scoreType:"critic", hltb:"30h", blurb:"Les frères plongent dans les rêves de Luigi, démultiplié à l'infini."},
        {slug:"inazuma-eleven-3", title:"Inazuma Eleven 3 (DS)", date:"2013-09-27", score:76, scoreType:"critic", hltb:"40h", blurb:"Coupe du monde et techniques surpuissantes, conclusion de la trilogie."},
        {slug:"rune-factory-4", title:"Rune Factory 4 (3DS)", date:"2013-10-01", score:78, scoreType:"critic", hltb:"55h", blurb:"Ferme, romance et donjons, le mariage parfait des genres."},
        {slug:"pokemon-x-y", title:"Pokémon X / Y (3DS)", date:"2013-10-12", score:84, scoreType:"user", hltb:"32h", blurb:"Le passage de Pokémon à la 3D, avec Kalos et les méga-évolutions."},
        {slug:"bravely-default", title:"Bravely Default (3DS)", date:"2014-02-07", score:84, scoreType:"user", hltb:"50h", blurb:"Le RPG old-school de Square Enix, avec son système Brave et Default."},
        {slug:"dark-souls-2", title:"Dark Souls II (PS3)", date:"2014-03-11", score:91, scoreType:"critic", hltb:"45h", blurb:"Drangleic et ses cycles de malédiction, suite plus vaste."},
        {slug:"fantasy-life", title:"Fantasy Life (3DS)", date:"2014-10-24", score:84, scoreType:"user", hltb:"40h", blurb:"RPG de vie de Level-5 où l'on enchaîne douze métiers avec bonheur."},
        {slug:"pokemon-omega-ruby-alpha-sapphire", title:"Pokémon Rubis Oméga / Saphir Alpha (3DS)", date:"2014-11-21", score:84, scoreType:"user", hltb:"30h", blurb:"Hoenn refait en 3D, avec l'envol libre à dos de Pokémon."},
        {slug:"persona-q-shadow-of-the-labyrinth", title:"Persona Q: Shadow of the Labyrinth (3DS)", date:"2014-11-25", score:80, scoreType:"critic", hltb:"60h", blurb:"Les castings de Persona 3 et 4 réunis dans un labyrinthe façon Etrian."},
        {slug:"smt-devil-survivor-2-record-breaker", title:"Shin Megami Tensei: Devil Survivor 2 Record Breaker (3DS)", date:"2015-05-05", score:81, scoreType:"critic", hltb:"40h", blurb:"Les Septentriones assiègent le Japon, version définitive avec épilogue complet."},
        {slug:"etrian-odyssey-2-untold", title:"Etrian Odyssey 2 Untold: The Fafnir Knight (3DS)", date:"2015-08-04", score:80, scoreType:"critic", hltb:"40h", blurb:"Le deuxième labyrinthe refait avec mode histoire, version définitive."},
        {slug:"stella-glow", title:"Stella Glow (3DS)", date:"2015-11-17", score:77, scoreType:"critic", hltb:"40h", blurb:"Tactical-RPG de sorcières chanteuses, chant du cygne d'Imageepoch."},
        {slug:"fire-emblem-fates", title:"Fire Emblem Fates (3DS)", date:"2016-02-19", score:82, scoreType:"user", hltb:"30h", blurb:"Deux familles, deux voies : Héritage accessible ou Conquête exigeante."},
        {slug:"bravely-second-end-layer", title:"Bravely Second: End Layer (3DS)", date:"2016-04-15", score:81, scoreType:"critic", hltb:"45h", blurb:"Suite directe de Bravely Default, système de jobs encore affiné."},
        {slug:"7th-dragon-3-code-vfd", title:"7th Dragon III Code: VFD (3DS)", date:"2016-07-12", score:76, scoreType:"critic", hltb:"30h", blurb:"Chasse aux dragons à travers les époques, seul épisode sorti en Occident."},
        {slug:"smt-4-apocalypse", title:"Shin Megami Tensei IV: Apocalypse (3DS)", date:"2016-09-20", score:84, scoreType:"critic", hltb:"40h", blurb:"Relecture de SMT IV du point de vue d'un chasseur ressuscité."},
        {slug:"yo-kai-watch-2", title:"Yo-kai Watch 2 (3DS)", date:"2016-09-30", score:80, scoreType:"critic", hltb:"40h", blurb:"Guerre d'esprits entre deux versions, l'épisode le plus complet de la série."},
        {slug:"persona-5", title:"Persona 5 (PS3)", date:"2017-04-04", score:92, scoreType:"user", hltb:"90h", blurb:"Les Voleurs Fantômes s'attaquent aux coeurs corrompus, style inégalé."},
        {slug:"fire-emblem-echoes-shadows-of-valentia", title:"Fire Emblem Echoes: Shadows of Valentia (3DS)", date:"2017-05-19", score:86, scoreType:"user", hltb:"30h", blurb:"Remake de Gaiden, doublé intégral et direction artistique superbe."},
        {slug:"ever-oasis", title:"Ever Oasis (3DS)", date:"2017-06-23", score:77, scoreType:"critic", hltb:"25h", blurb:"Bâtir une oasis et explorer le désert, ultime charme signé Grezzo."},
        {slug:"monster-hunter-stories", title:"Monster Hunter Stories (3DS)", date:"2017-09-08", score:81, scoreType:"critic", hltb:"35h", blurb:"Monster Hunter en RPG au tour par tour, monstres à élever."},
        {slug:"pokemon-ultra-sun-ultra-moon", title:"Pokémon Ultra-Soleil / Ultra-Lune (3DS)", date:"2017-11-17", score:84, scoreType:"critic", hltb:"35h", blurb:"Version définitive d'Alola, ultime épisode Pokémon de la 3DS."},
        {slug:"radiant-historia-perfect-chronology", title:"Radiant Historia: Perfect Chronology (3DS)", date:"2018-02-13", score:83, scoreType:"critic", hltb:"35h", blurb:"Le RPG temporel dans sa version définitive, troisième ligne d'histoire incluse."},
        {slug:"the-alliance-alive", title:"The Alliance Alive (3DS)", date:"2018-03-27", score:76, scoreType:"critic", hltb:"35h", blurb:"Hommage aux RPG SaGa, neuf héros sous un ciel confisqué."},
        {slug:"etrian-odyssey-nexus", title:"Etrian Odyssey Nexus (3DS)", date:"2019-02-05", score:81, scoreType:"critic", hltb:"60h", blurb:"Le grand best-of des labyrinthes, adieu de la série à la 3DS."},
        {slug:"persona-q2-new-cinema-labyrinth", title:"Persona Q2: New Cinema Labyrinth (3DS)", date:"2019-06-04", score:78, scoreType:"critic", hltb:"50h", blurb:"Les héros de Persona 3, 4 et 5 piégés dans un cinéma."}
      ]
    }
  }
};

// Exposé en global pour que la page fonctionne aussi ouverte en file://
// (les imports de modules ES sont bloqués hors serveur HTTP).
if (typeof window !== "undefined") window.ODYSSEY_DATA = DATA;
