/* ===========================================================
   Données du site — Mon Périple Vidéoludique
   Un objet par console. "games" est trié par date de sortie.
   score / scoreType: scoreType "user" = note utilisateurs
   Metacritic (x10, ex. 8.9 -> 89) ; "critic" = Metascore critique
   utilisé quand la note utilisateurs n'est pas disponible ;
   null = aucune note Metacritic (ex. sortie Japon uniquement).
   =========================================================== */

const DATA = {
  consoles: {
    gba: {
      key: "gba",
      name: "Game Boy Advance",
      short: "GBA",
      color: "#8fae52",
      theme: "assets/theme-gba.css",
      page: "gba.html",
      ready: true,
      games: [
        {slug:"castlevania-circle-of-the-moon", title:"Castlevania: Circle of the Moon", date:"2001-06-11", score:84, scoreType:"critic", hltb:"8h", blurb:"Premier Castlevania \"Metroidvania\" portable, sombre et exigeant."},
        {slug:"super-mario-advance", title:"Super Mario Advance", date:"2001-06-11", score:79, scoreType:"critic", hltb:"3h", blurb:"Portage 16 bits de Super Mario Bros. 2, avec Mario Bros. en bonus."},
        {slug:"kuru-kuru-kururin", title:"Kuru Kuru Kururin", date:"2001-08-10", score:78, scoreType:"critic", hltb:"4h", blurb:"Puzzle-action minimaliste : guider une hélice tournante sans toucher les murs."},
        {slug:"mario-kart-super-circuit", title:"Mario Kart: Super Circuit", date:"2001-08-27", score:84, scoreType:"critic", hltb:"6h", blurb:"Premier Mario Kart portable, avec tous les circuits de la SNES en bonus."},
        {slug:"f-zero-maximum-velocity", title:"F-Zero: Maximum Velocity", date:"2001-08-10", score:78, scoreType:"critic", hltb:"5h", blurb:"Course futuriste ultra-rapide, exigeante et sans fioritures."},
        {slug:"advance-wars", title:"Advance Wars", date:"2001-09-09", score:86, scoreType:"user", hltb:"14h", blurb:"Stratégie tour par tour culte qui a lancé toute une série."},
        {slug:"klonoa-empire-of-dreams", title:"Klonoa: Empire of Dreams", date:"2001-11-14", score:79, scoreType:"critic", hltb:"5h", blurb:"Plateforme onirique signée Namco, charme et level design soignés."},
        {slug:"golden-sun", title:"Golden Sun", date:"2001-11-11", score:89, scoreType:"user", hltb:"19h", blurb:"RPG au tour par tour avec un système de Psynergie marquant."},
        {slug:"wario-land-4", title:"Wario Land 4", date:"2001-11-18", score:87, scoreType:"user", hltb:"6h", blurb:"Plateforme non-linéaire à la direction artistique et sonore culte."},
        {slug:"tactics-ogre-the-knight-of-lodis", title:"Tactics Ogre: The Knight of Lodis", date:"2001-11-21", score:82, scoreType:"critic", hltb:"35h", blurb:"Tactical-RPG exigeant, préquelle des épisodes SNES/N64."},
        {slug:"super-mario-world-super-mario-advance-2", title:"Super Mario World: Super Mario Advance 2", date:"2002-02-09", score:88, scoreType:"user", hltb:"8h", blurb:"Le classique SNES intégral, avec toutes les sorties secrètes."},
        {slug:"sonic-advance", title:"Sonic Advance", date:"2002-02-19", score:79, scoreType:"critic", hltb:"4h", blurb:"Le retour du hérisson en 2D par Dimps, vitesse et level design réussis."},
        {slug:"castlevania-harmony-of-dissonance", title:"Castlevania: Harmony of Dissonance", date:"2002-06-06", score:79, scoreType:"critic", hltb:"8h", blurb:"Deuxième Castlevania GBA, plus lumineux, avec Juste Belmont."},
        {slug:"yoshis-island-super-mario-advance-3", title:"Yoshi's Island: Super Mario Advance 3", date:"2002-09-24", score:89, scoreType:"user", hltb:"8h", blurb:"Le chef-d'oeuvre SNES intact, exploration et direction artistique pastel."},
        {slug:"metroid-fusion", title:"Metroid Fusion", date:"2002-11-17", score:88, scoreType:"user", hltb:"6h", blurb:"Suite directe de Super Metroid, tension et progression exemplaires."},
        {slug:"zelda-a-link-to-the-past-four-swords", title:"The Legend of Zelda: A Link to the Past & Four Swords", date:"2002-12-03", score:88, scoreType:"user", hltb:"10h", blurb:"Le classique SNES plus un mode multijoueur inédit, Four Swords."},
        {slug:"kirby-nightmare-in-dream-land", title:"Kirby: Nightmare in Dream Land", date:"2002-12-16", score:79, scoreType:"critic", hltb:"5h", blurb:"Remake du tout premier Kirby, doux et accessible."},
        {slug:"sonic-advance-2", title:"Sonic Advance 2", date:"2002-12-20", score:80, scoreType:"critic", hltb:"4h", blurb:"Suite plus rapide et plus exigeante, Tiny Chao Garden inclus."},
        {slug:"final-fantasy-tactics-advance", title:"Final Fantasy Tactics Advance", date:"2003-02-14", score:84, scoreType:"critic", hltb:"35h", blurb:"Tactical-RPG dans un monde imaginé par un enfant, riche et long."},
        {slug:"golden-sun-the-lost-age", title:"Golden Sun: The Lost Age", date:"2003-04-14", score:89, scoreType:"user", hltb:"24h", blurb:"Suite directe de Golden Sun, poursuite de l'aventure et des Psynergies."},
        {slug:"castlevania-aria-of-sorrow", title:"Castlevania: Aria of Sorrow", date:"2003-05-06", score:89, scoreType:"user", hltb:"8h", blurb:"Sommet de la trilogie GBA, système d'âmes profond, souvent cité comme le meilleur."},
        {slug:"warioware-inc-mega-microgames", title:"WarioWare, Inc.: Mega Microgame$!", date:"2003-05-26", score:85, scoreType:"user", hltb:"2h", blurb:"Plus de 200 micro-jeux frénétiques, format culte et addictif."},
        {slug:"donkey-kong-country", title:"Donkey Kong Country", date:"2003-06-09", score:87, scoreType:"user", hltb:"8h", blurb:"Portage du classique SNES, toujours aussi solide."},
        {slug:"dragon-ball-z-legacy-of-goku-2", title:"Dragon Ball Z: The Legacy of Goku II", date:"2003-06-17", score:88, scoreType:"user", hltb:"12h", blurb:"Action-RPG dans l'univers DBZ, de la saga Cell à Buu."},
        {slug:"mega-man-battle-network-3", title:"Mega Man Battle Network 3", date:"2003-06-18", score:83, scoreType:"critic", hltb:"18h", blurb:"RPG tactique en réseau, l'un des sommets de la série."},
        {slug:"advance-wars-2-black-hole-rising", title:"Advance Wars 2: Black Hole Rising", date:"2003-06-23", score:88, scoreType:"critic", hltb:"15h", blurb:"Suite plus équilibrée, avec une nouvelle campagne solo."},
        {slug:"boktai-the-sun-is-in-your-hand", title:"Boktai: The Sun Is in Your Hand", date:"2003-09-29", score:76, scoreType:"critic", hltb:"12h", blurb:"Chasseur de vampires avec un capteur solaire intégré à la cartouche."},
        {slug:"super-mario-advance-4-smb3", title:"Super Mario Advance 4: Super Mario Bros. 3", date:"2003-10-21", score:86, scoreType:"user", hltb:"6h", blurb:"Le classique NES avec une carte du monde inédite."},
        {slug:"fire-emblem", title:"Fire Emblem", date:"2003-11-03", score:89, scoreType:"user", hltb:"25h", blurb:"Premier épisode occidental de la saga, tactique et permadeath."},
        {slug:"sword-of-mana", title:"Sword of Mana", date:"2003-11-11", score:71, scoreType:"critic", hltb:"15h", blurb:"Remake de Seiken Densetsu, deux personnages jouables au choix."},
        {slug:"mario-and-luigi-superstar-saga", title:"Mario & Luigi: Superstar Saga", date:"2003-11-17", score:86, scoreType:"user", hltb:"15h", blurb:"RPG humoristique en duo, combos et timing à la clé."},
        {slug:"kingdom-hearts-chain-of-memories", title:"Kingdom Hearts: Chain of Memories", date:"2003-12-07", score:82, scoreType:"critic", hltb:"13h", blurb:"Spin-off à système de cartes, entre deux épisodes canoniques."},
        {slug:"metroid-zero-mission", title:"Metroid: Zero Mission", date:"2004-02-09", score:89, scoreType:"user", hltb:"6h", blurb:"Remake du Metroid original, avec une toute nouvelle fin."},
        {slug:"mega-man-zero-3", title:"Mega Man Zero 3", date:"2004-04-15", score:81, scoreType:"critic", hltb:"4h", blurb:"Troisième volet, affine la formule sans bouleverser l'équilibre."},
        {slug:"mario-vs-donkey-kong", title:"Mario vs. Donkey Kong", date:"2004-06-09", score:84, scoreType:"critic", hltb:"5h", blurb:"Casse-tête de plateforme qui lance la série du même nom."},
        {slug:"astro-boy-omega-factor", title:"Astro Boy: Omega Factor", date:"2004-08-17", score:85, scoreType:"critic", hltb:"4h", blurb:"Beat'em up signé Treasure, hommage complet à l'oeuvre de Tezuka."},
        {slug:"pokemon-firered-leafgreen", title:"Pokémon FireRed / LeafGreen", date:"2004-09-07", score:85, scoreType:"user", hltb:"24h", blurb:"Remake de la toute première génération Pokémon."},
        {slug:"dragon-ball-z-buus-fury", title:"Dragon Ball Z: Buu's Fury", date:"2004-09-14", score:86, scoreType:"user", hltb:"15h", blurb:"Suite directe de Legacy of Goku II, jusqu'à la saga Buu."},
        {slug:"kirby-and-the-amazing-mirror", title:"Kirby & the Amazing Mirror", date:"2004-10-18", score:85, scoreType:"user", hltb:"6h", blurb:"Exploration façon Metroidvania avec jusqu'à 4 Kirby en simultané."},
        {slug:"donkey-kong-country-2-diddys-kong-quest", title:"Donkey Kong Country 2: Diddy's Kong Quest", date:"2004-11-15", score:88, scoreType:"user", hltb:"9h", blurb:"Portage du meilleur épisode SNES de la trilogie DKC."},
        {slug:"zelda-the-minish-cap", title:"The Legend of Zelda: The Minish Cap", date:"2005-01-10", score:88, scoreType:"user", hltb:"11h", blurb:"Link rétrécit pour explorer un monde miniature, très bien noté."},
        {slug:"pokemon-emerald", title:"Pokémon Emerald", date:"2005-04-30", score:88, scoreType:"user", hltb:"24h", blurb:"Version augmentée de Ruby/Sapphire, contenu post-jeu étoffé."},
        {slug:"fire-emblem-the-sacred-stones", title:"Fire Emblem: The Sacred Stones", date:"2005-05-23", score:87, scoreType:"user", hltb:"20h", blurb:"Dernier Fire Emblem GBA, jumeaux royaux et monde ouvert."},
        {slug:"gunstar-super-heroes", title:"Gunstar Super Heroes", date:"2005-07-28", score:76, scoreType:"critic", hltb:"3h", blurb:"Run and gun nerveux signé Treasure, suite de Gunstar Heroes."},
        {slug:"drill-dozer", title:"Drill Dozer", date:"2005-09-15", score:76, scoreType:"critic", hltb:"5h", blurb:"Plateforme à la perceuse par Game Freak, hors Pokémon."},
        {slug:"pokemon-mystery-dungeon-red-rescue-team", title:"Pokémon Mystery Dungeon: Red Rescue Team", date:"2005-11-17", score:71, scoreType:"critic", hltb:"20h", blurb:"Donjons procéduraux : incarnez un Pokémon dans un monde de Pokémon."},
        {slug:"final-fantasy-4-advance", title:"Final Fantasy IV Advance", date:"2005-12-12", score:80, scoreType:"critic", hltb:"20h", blurb:"Portage enrichi du classique SNES, nouveaux donjons."},
        {slug:"mother-3", title:"Mother 3", date:"2006-04-20", score:null, scoreType:"none", hltb:"20h", blurb:"Suite culte d'Earthbound, jamais sortie officiellement hors Japon."},
        {slug:"dragon-ball-advanced-adventure", title:"Dragon Ball: Advanced Adventure", date:"2006-06-06", score:86, scoreType:"user", hltb:"6h", blurb:"Retour aux origines de Dragon Ball, l'enfance de Goku."},
        {slug:"final-fantasy-5-advance", title:"Final Fantasy V Advance", date:"2006-11-06", score:76, scoreType:"critic", hltb:"25h", blurb:"Portage du système de jobs, très apprécié des puristes."}
      ]
    },

    ds: {
      key: "ds",
      name: "Nintendo DS",
      short: "DS",
      color: "#3d6a91",
      theme: "assets/theme-ds.css",
      page: "ds.html",
      ready: true,
      games: [
        {slug:"super-mario-64-ds", title:"Super Mario 64 DS", date:"2004-11-21", score:85, scoreType:"user", hltb:"10h", blurb:"Portage enrichi du classique N64, avec Yoshi, Luigi et Wario jouables."},
        {slug:"warioware-touched", title:"WarioWare: Touched!", date:"2005-02-14", score:81, scoreType:"critic", hltb:"3h", blurb:"Micro-jeux entièrement au stylet, la frénésie WarioWare en version tactile."},
        {slug:"kirby-canvas-curse", title:"Kirby: Canvas Curse", date:"2005-06-13", score:86, scoreType:"critic", hltb:"5h", blurb:"Kirby guidé en traçant des arcs-en-ciel au stylet, première grande réussite tactile de la DS."},
        {slug:"meteos", title:"Meteos", date:"2005-06-28", score:88, scoreType:"critic", hltb:"4h", blurb:"Puzzle cosmique de Masahiro Sakurai où l'on renvoie les blocs dans l'espace."},
        {slug:"nintendogs", title:"Nintendogs", date:"2005-08-22", score:83, scoreType:"critic", hltb:"20h", blurb:"Phénomène de société : élever et dresser son chiot au stylet et à la voix."},
        {slug:"advance-wars-dual-strike", title:"Advance Wars: Dual Strike", date:"2005-08-22", score:88, scoreType:"user", hltb:"25h", blurb:"La stratégie culte passe sur deux écrans avec les duos de généraux."},
        {slug:"castlevania-dawn-of-sorrow", title:"Castlevania: Dawn of Sorrow", date:"2005-10-04", score:88, scoreType:"user", hltb:"9h", blurb:"Suite directe d'Aria of Sorrow, Metroidvania de référence de la console."},
        {slug:"phoenix-wright-ace-attorney", title:"Phoenix Wright: Ace Attorney", date:"2005-10-11", score:89, scoreType:"user", hltb:"15h", blurb:"Les premiers procès d'un avocat de légende : objection !"},
        {slug:"mario-kart-ds", title:"Mario Kart DS", date:"2005-11-14", score:88, scoreType:"user", hltb:"6h", blurb:"Premier Mario Kart jouable en ligne, avec circuits rétro et mode missions."},
        {slug:"sonic-rush", title:"Sonic Rush", date:"2005-11-15", score:82, scoreType:"critic", hltb:"4h", blurb:"Sonic à toute vitesse sur deux écrans, avec Blaze et la jauge de boost."},
        {slug:"mario-and-luigi-partners-in-time", title:"Mario & Luigi: Partners in Time", date:"2005-11-28", score:85, scoreType:"user", hltb:"17h", blurb:"Les frères voyagent dans le temps aux côtés de leurs versions bébés."},
        {slug:"animal-crossing-wild-world", title:"Animal Crossing: Wild World", date:"2005-12-05", score:84, scoreType:"user", hltb:"40h", blurb:"Le village d'Animal Crossing en poche, visites d'amis en ligne comprises."},
        {slug:"metroid-prime-hunters", title:"Metroid Prime Hunters", date:"2006-03-20", score:85, scoreType:"critic", hltb:"9h", blurb:"FPS techniquement impressionnant, visée au stylet et multijoueur en ligne."},
        {slug:"tetris-ds", title:"Tetris DS", date:"2006-03-20", score:83, scoreType:"critic", hltb:"8h", blurb:"Tetris habillé aux couleurs des classiques Nintendo, redoutable en ligne."},
        {slug:"new-super-mario-bros", title:"New Super Mario Bros.", date:"2006-05-15", score:85, scoreType:"user", hltb:"7h", blurb:"Le grand retour du Mario 2D, le premier épisode inédit depuis la SNES."},
        {slug:"elite-beat-agents", title:"Elite Beat Agents", date:"2006-11-06", score:88, scoreType:"user", hltb:"6h", blurb:"Jeu de rythme au stylet où des agents en costume sauvent des vies en musique."},
        {slug:"final-fantasy-3", title:"Final Fantasy III", date:"2006-11-14", score:77, scoreType:"critic", hltb:"30h", blurb:"Remake 3D du seul Final Fantasy alors jamais sorti du Japon."},
        {slug:"castlevania-portrait-of-ruin", title:"Castlevania: Portrait of Ruin", date:"2006-12-05", score:87, scoreType:"user", hltb:"9h", blurb:"Metroidvania en duo, Jonathan et Charlotte explorent des tableaux maudits."},
        {slug:"hotel-dusk-room-215", title:"Hotel Dusk: Room 215", date:"2007-01-22", score:78, scoreType:"critic", hltb:"15h", blurb:"Polar interactif au crayonné unique, console tenue comme un livre."},
        {slug:"pokemon-diamond-pearl", title:"Pokémon Diamant / Perle", date:"2007-04-22", score:85, scoreType:"user", hltb:"40h", blurb:"Quatrième génération à Sinnoh, avec les échanges Wi-Fi mondiaux."},
        {slug:"picross-ds", title:"Picross DS", date:"2007-07-30", score:83, scoreType:"critic", hltb:"30h", blurb:"Des centaines de grilles de logique, parfaites au stylet."},
        {slug:"zelda-phantom-hourglass", title:"The Legend of Zelda: Phantom Hourglass", date:"2007-10-01", score:90, scoreType:"critic", hltb:"15h", blurb:"Suite directe de Wind Waker, entièrement jouée au stylet."},
        {slug:"phoenix-wright-trials-and-tribulations", title:"Phoenix Wright: Trials and Tribulations", date:"2007-10-23", score:90, scoreType:"user", hltb:"18h", blurb:"Conclusion magistrale de la trilogie Phoenix Wright."},
        {slug:"contra-4", title:"Contra 4", date:"2007-11-13", score:83, scoreType:"critic", hltb:"3h", blurb:"Run and gun hardcore sur deux écrans, hommage aux origines de la série."},
        {slug:"advance-wars-days-of-ruin", title:"Advance Wars: Days of Ruin", date:"2008-01-21", score:86, scoreType:"critic", hltb:"25h", blurb:"Advance Wars post-apocalyptique, plus sombre et rééquilibré."},
        {slug:"professor-layton-curious-village", title:"Professeur Layton et l'Étrange Village", date:"2008-02-10", score:88, scoreType:"user", hltb:"12h", blurb:"Énigmes élégantes et village mystérieux, naissance d'une série culte."},
        {slug:"the-world-ends-with-you", title:"The World Ends with You", date:"2008-04-22", score:90, scoreType:"user", hltb:"20h", blurb:"RPG d'action ultra-stylé dans Shibuya, combats sur les deux écrans."},
        {slug:"final-fantasy-tactics-a2", title:"Final Fantasy Tactics A2: Grimoire of the Rift", date:"2008-06-24", score:80, scoreType:"critic", hltb:"40h", blurb:"Tactical-RPG généreux dans le monde d'Ivalice."},
        {slug:"dragon-quest-4", title:"Dragon Quest IV: L'Épopée des Élus", date:"2008-09-16", score:80, scoreType:"critic", hltb:"30h", blurb:"Remake du classique NES raconté en chapitres, un par héros."},
        {slug:"kirby-super-star-ultra", title:"Kirby Super Star Ultra", date:"2008-09-22", score:89, scoreType:"user", hltb:"8h", blurb:"Remake de Super Star et ses nombreux modes, l'un des meilleurs Kirby."},
        {slug:"castlevania-order-of-ecclesia", title:"Castlevania: Order of Ecclesia", date:"2008-10-21", score:87, scoreType:"user", hltb:"10h", blurb:"Dernier Castlevania DS, exigeant, avec Shanoa et son système de glyphes."},
        {slug:"chrono-trigger", title:"Chrono Trigger", date:"2008-11-25", score:91, scoreType:"user", hltb:"23h", blurb:"Le voyage temporel légendaire de la SNES, enfin portable."},
        {slug:"fire-emblem-shadow-dragon", title:"Fire Emblem: Shadow Dragon", date:"2009-02-16", score:81, scoreType:"critic", hltb:"20h", blurb:"Remake du tout premier Fire Emblem, avec Marth."},
        {slug:"dragon-quest-5", title:"Dragon Quest V: La Fiancée Céleste", date:"2009-02-17", score:89, scoreType:"user", hltb:"30h", blurb:"Une vie entière racontée, souvent cité comme le sommet de la saga."},
        {slug:"gta-chinatown-wars", title:"Grand Theft Auto: Chinatown Wars", date:"2009-03-17", score:93, scoreType:"critic", hltb:"12h", blurb:"GTA vu du dessus étonnamment complet, taillé sur mesure pour la DS."},
        {slug:"pokemon-platinum", title:"Pokémon Platine", date:"2009-03-22", score:88, scoreType:"user", hltb:"40h", blurb:"Version définitive de Sinnoh, avec le Monde Distorsion."},
        {slug:"rhythm-heaven", title:"Rhythm Heaven", date:"2009-04-05", score:85, scoreType:"user", hltb:"8h", blurb:"Mini-jeux de rythme absurdes et irrésistibles, au tapotement du stylet."},
        {slug:"professor-layton-diabolical-box", title:"Professeur Layton et la Boîte de Pandore", date:"2009-08-24", score:84, scoreType:"critic", hltb:"13h", blurb:"Deuxième enquête du professeur, à bord du Molentary Express."},
        {slug:"mario-and-luigi-bowsers-inside-story", title:"Mario & Luigi: Voyage au centre de Bowser", date:"2009-09-14", score:89, scoreType:"user", hltb:"25h", blurb:"Mario et Luigi explorent l'intérieur de Bowser, sommet de la série."},
        {slug:"might-and-magic-clash-of-heroes", title:"Might & Magic: Clash of Heroes", date:"2009-12-01", score:87, scoreType:"critic", hltb:"18h", blurb:"Puzzle-stratégie inventif dans l'univers de Might & Magic."},
        {slug:"zelda-spirit-tracks", title:"The Legend of Zelda: Spirit Tracks", date:"2009-12-07", score:87, scoreType:"critic", hltb:"18h", blurb:"Link conducteur de train, accompagné du fantôme de la princesse Zelda."},
        {slug:"pokemon-heartgold-soulsilver", title:"Pokémon HeartGold / SoulSilver", date:"2010-03-14", score:90, scoreType:"user", hltb:"40h", blurb:"Remake de la deuxième génération, Johto et Kanto réunis, Pokéwalker inclus."},
        {slug:"smt-strange-journey", title:"Shin Megami Tensei: Strange Journey", date:"2010-03-23", score:80, scoreType:"critic", hltb:"40h", blurb:"Expédition SMT pure et dure en Antarctique, sombre et fascinante."},
        {slug:"picross-3d", title:"Picross 3D", date:"2010-05-03", score:82, scoreType:"critic", hltb:"25h", blurb:"Le picross passe en trois dimensions : on sculpte les blocs au stylet."},
        {slug:"dragon-quest-9", title:"Dragon Quest IX: Les Sentinelles du Firmament", date:"2010-07-11", score:85, scoreType:"user", hltb:"40h", blurb:"Épisode pensé pour le jeu en groupe, au contenu immense."},
        {slug:"professor-layton-unwound-future", title:"Professeur Layton et le Destin Perdu", date:"2010-09-12", score:89, scoreType:"user", hltb:"12h", blurb:"Le voyage dans le temps le plus émouvant du professeur."},
        {slug:"999-nine-hours-nine-persons-nine-doors", title:"999: Nine Hours, Nine Persons, Nine Doors", date:"2010-11-16", score:90, scoreType:"user", hltb:"10h", blurb:"Visual novel à énigmes sous tension, neuf personnes piégées sur un navire."},
        {slug:"ghost-trick-phantom-detective", title:"Ghost Trick: Phantom Detective", date:"2011-01-11", score:90, scoreType:"user", hltb:"12h", blurb:"Sitôt mort, Sissel manipule les objets pour changer le destin des vivants."},
        {slug:"radiant-historia", title:"Radiant Historia", date:"2011-02-22", score:88, scoreType:"user", hltb:"30h", blurb:"RPG à voyages temporels entre deux lignes d'histoire parallèles."},
        {slug:"pokemon-black-white", title:"Pokémon Noir / Blanc", date:"2011-03-06", score:82, scoreType:"user", hltb:"32h", blurb:"Cinquième génération à Unys, avec uniquement de nouveaux Pokémon."}
      ]
    },

    n3ds: {
      key: "n3ds",
      name: "Nintendo 3DS",
      short: "3DS",
      color: "#ff2ea6",
      theme: "assets/theme-3ds.css",
      page: "3ds.html",
      ready: true,
      games: [
        {slug:"super-street-fighter-4-3d", title:"Super Street Fighter IV: 3D Edition", date:"2011-03-27", score:85, scoreType:"critic", hltb:"12h", blurb:"Le grand jeu de combat de Capcom en poche dès le lancement de la console."},
        {slug:"zelda-ocarina-of-time-3d", title:"The Legend of Zelda: Ocarina of Time 3D", date:"2011-06-19", score:91, scoreType:"user", hltb:"26h", blurb:"Le chef-d'oeuvre N64 remis à neuf, avec la Master Quest en bonus."},
        {slug:"star-fox-64-3d", title:"Star Fox 64 3D", date:"2011-09-09", score:81, scoreType:"critic", hltb:"2h", blurb:"Lylat Wars remasterisé, parfait pour des sessions courtes et rejouables."},
        {slug:"super-mario-3d-land", title:"Super Mario 3D Land", date:"2011-11-13", score:87, scoreType:"user", hltb:"6h", blurb:"Pont malin entre Mario 2D et 3D, pensé pour l'écran stéréoscopique."},
        {slug:"mario-kart-7", title:"Mario Kart 7", date:"2011-12-04", score:85, scoreType:"user", hltb:"5h", blurb:"Deltaplanes et sections sous-marines rejoignent la formule Mario Kart."},
        {slug:"pushmo", title:"Pushmo", date:"2011-12-08", score:87, scoreType:"critic", hltb:"12h", blurb:"Puzzle d'escalade ingénieux, pépite eShop signée Intelligent Systems."},
        {slug:"resident-evil-revelations", title:"Resident Evil Revelations", date:"2012-02-07", score:82, scoreType:"critic", hltb:"9h", blurb:"Survival horror ambitieux en mer, épisode canonique taillé pour la portable."},
        {slug:"kid-icarus-uprising", title:"Kid Icarus: Uprising", date:"2012-03-23", score:87, scoreType:"user", hltb:"11h", blurb:"Le retour de Pit par Masahiro Sakurai, dialogues savoureux et action intense."},
        {slug:"kingdom-hearts-3d-dream-drop-distance", title:"Kingdom Hearts 3D: Dream Drop Distance", date:"2012-07-31", score:75, scoreType:"critic", hltb:"17h", blurb:"Sora et Riku alternent dans les mondes endormis, étape clé de l'intrigue."},
        {slug:"new-super-mario-bros-2", title:"New Super Mario Bros. 2", date:"2012-08-19", score:78, scoreType:"critic", hltb:"7h", blurb:"Mario 2D placé sous le signe de la ruée vers l'or et du million de pièces."},
        {slug:"zero-escape-virtues-last-reward", title:"Zero Escape: Virtue's Last Reward", date:"2012-10-23", score:88, scoreType:"user", hltb:"30h", blurb:"Suite de 999, huis clos à embranchements où chaque trahison compte."},
        {slug:"professor-layton-miracle-mask", title:"Professeur Layton et le Masque des Miracles", date:"2012-10-28", score:81, scoreType:"critic", hltb:"15h", blurb:"Cinquième enquête du professeur, entre cirque et cité du désert."},
        {slug:"fire-emblem-awakening", title:"Fire Emblem: Awakening", date:"2013-02-04", score:89, scoreType:"user", hltb:"25h", blurb:"L'épisode qui a sauvé la série, avec mariages et enfants entre unités."},
        {slug:"etrian-odyssey-4", title:"Etrian Odyssey IV: Legends of the Titan", date:"2013-02-26", score:82, scoreType:"critic", hltb:"40h", blurb:"Dungeon-RPG où l'on dessine soi-même sa carte sur l'écran tactile."},
        {slug:"monster-hunter-3-ultimate", title:"Monster Hunter 3 Ultimate", date:"2013-03-19", score:85, scoreType:"critic", hltb:"50h", blurb:"La chasse aux monstres dans sa version la plus complète de l'ère Tri."},
        {slug:"luigis-mansion-dark-moon", title:"Luigi's Mansion: Dark Moon", date:"2013-03-24", score:84, scoreType:"user", hltb:"12h", blurb:"Luigi reprend l'aspirateur à fantômes à travers cinq manoirs variés."},
        {slug:"donkey-kong-country-returns-3d", title:"Donkey Kong Country Returns 3D", date:"2013-05-24", score:78, scoreType:"critic", hltb:"8h", blurb:"Le retour exigeant de la famille Kong, adapté du jeu Wii."},
        {slug:"animal-crossing-new-leaf", title:"Animal Crossing: New Leaf", date:"2013-06-09", score:88, scoreType:"user", hltb:"60h", blurb:"Cette fois c'est vous le maire : l'épisode qui a conquis le monde entier."},
        {slug:"shin-megami-tensei-4", title:"Shin Megami Tensei IV", date:"2013-07-16", score:83, scoreType:"critic", hltb:"45h", blurb:"Apocalypse démoniaque entre royaume médiéval et Tokyo en ruines."},
        {slug:"mario-and-luigi-dream-team", title:"Mario & Luigi: Dream Team", date:"2013-08-11", score:81, scoreType:"critic", hltb:"30h", blurb:"Les frères plongent dans les rêves de Luigi, démultiplié à l'infini."},
        {slug:"pokemon-x-y", title:"Pokémon X / Y", date:"2013-10-12", score:84, scoreType:"user", hltb:"32h", blurb:"Le passage de Pokémon à la 3D, avec Kalos et les méga-évolutions."},
        {slug:"phoenix-wright-dual-destinies", title:"Phoenix Wright: Ace Attorney - Dual Destinies", date:"2013-10-24", score:81, scoreType:"critic", hltb:"20h", blurb:"Phoenix reprend le barreau dans une ère sombre du droit."},
        {slug:"zelda-a-link-between-worlds", title:"The Legend of Zelda: A Link Between Worlds", date:"2013-11-22", score:90, scoreType:"user", hltb:"16h", blurb:"Hyrule d'A Link to the Past revisité, Link se fond dans les murs."},
        {slug:"bravely-default", title:"Bravely Default", date:"2014-02-07", score:84, scoreType:"user", hltb:"50h", blurb:"Le RPG old-school de Square Enix, avec son système Brave et Default."},
        {slug:"kirby-triple-deluxe", title:"Kirby: Triple Deluxe", date:"2014-05-02", score:80, scoreType:"critic", hltb:"6h", blurb:"Kirby joue sur la profondeur des deux plans grâce à la 3D."},
        {slug:"shovel-knight", title:"Shovel Knight", date:"2014-06-26", score:88, scoreType:"user", hltb:"6h", blurb:"Hommage parfait aux plateformers NES, à la pelle et au StreetPass."},
        {slug:"theatrhythm-final-fantasy-curtain-call", title:"Theatrhythm Final Fantasy: Curtain Call", date:"2014-09-16", score:84, scoreType:"critic", hltb:"15h", blurb:"Toute la musique de Final Fantasy en jeu de rythme encyclopédique."},
        {slug:"super-smash-bros-for-3ds", title:"Super Smash Bros. for Nintendo 3DS", date:"2014-10-03", score:84, scoreType:"user", hltb:"7h", blurb:"Premier Smash portable, avec le mode Aventure Smash exclusif."},
        {slug:"fantasy-life", title:"Fantasy Life", date:"2014-10-24", score:84, scoreType:"user", hltb:"40h", blurb:"RPG de vie de Level-5 où l'on enchaîne douze métiers avec bonheur."},
        {slug:"pokemon-omega-ruby-alpha-sapphire", title:"Pokémon Rubis Oméga / Saphir Alpha", date:"2014-11-21", score:84, scoreType:"user", hltb:"30h", blurb:"Hoenn refait en 3D, avec l'envol libre à dos de Pokémon."},
        {slug:"persona-q-shadow-of-the-labyrinth", title:"Persona Q: Shadow of the Labyrinth", date:"2014-11-25", score:80, scoreType:"critic", hltb:"60h", blurb:"Les castings de Persona 3 et 4 réunis dans un labyrinthe façon Etrian."},
        {slug:"zelda-majoras-mask-3d", title:"The Legend of Zelda: Majora's Mask 3D", date:"2015-02-13", score:89, scoreType:"user", hltb:"20h", blurb:"Les trois jours de Termina remasterisés, toujours aussi singuliers."},
        {slug:"monster-hunter-4-ultimate", title:"Monster Hunter 4 Ultimate", date:"2015-02-13", score:88, scoreType:"user", hltb:"60h", blurb:"La chasse gagne la verticalité et la monte, sommet de la série sur 3DS."},
        {slug:"boxboy", title:"BoxBoy!", date:"2015-04-02", score:80, scoreType:"critic", hltb:"5h", blurb:"Puzzle minimaliste de HAL : Qbby génère des boîtes pour progresser."},
        {slug:"xenoblade-chronicles-3d", title:"Xenoblade Chronicles 3D", date:"2015-04-10", score:86, scoreType:"critic", hltb:"60h", blurb:"L'immense RPG de Monolith Soft entier en poche, sur New 3DS uniquement."},
        {slug:"steamworld-heist", title:"SteamWorld Heist", date:"2015-12-10", score:87, scoreType:"critic", hltb:"15h", blurb:"Tactique au tour par tour où chaque tir se vise à la main, brillant."},
        {slug:"fire-emblem-fates", title:"Fire Emblem Fates", date:"2016-02-19", score:82, scoreType:"user", hltb:"30h", blurb:"Deux familles, deux voies : Héritage accessible ou Conquête exigeante."},
        {slug:"bravely-second-end-layer", title:"Bravely Second: End Layer", date:"2016-04-15", score:81, scoreType:"critic", hltb:"45h", blurb:"Suite directe de Bravely Default, système de jobs encore affiné."},
        {slug:"kirby-planet-robobot", title:"Kirby: Planet Robobot", date:"2016-06-10", score:87, scoreType:"user", hltb:"7h", blurb:"Kirby pilote une armure mécha, l'un des meilleurs épisodes de la série."},
        {slug:"rhythm-heaven-megamix", title:"Rhythm Heaven Megamix", date:"2016-06-15", score:84, scoreType:"critic", hltb:"8h", blurb:"Best-of de toute la série de rythme, nouveaux jeux inclus."},
        {slug:"monster-hunter-generations", title:"Monster Hunter Generations", date:"2016-07-15", score:85, scoreType:"critic", hltb:"50h", blurb:"Épisode anniversaire aux styles de chasse libres, hommage à la saga."},
        {slug:"phoenix-wright-spirit-of-justice", title:"Phoenix Wright: Ace Attorney - Spirit of Justice", date:"2016-09-08", score:81, scoreType:"critic", hltb:"25h", blurb:"Procès dans un royaume où l'on juge par les visions des morts."},
        {slug:"dragon-quest-7-3ds", title:"Dragon Quest VII: La Quête des vestiges du monde", date:"2016-09-16", score:78, scoreType:"critic", hltb:"60h", blurb:"Remake du géant PlayStation, des îles entières à ramener à la vie."},
        {slug:"pokemon-sun-moon", title:"Pokémon Soleil / Lune", date:"2016-11-18", score:80, scoreType:"user", hltb:"35h", blurb:"Direction Alola et ses formes régionales, sans arènes traditionnelles."},
        {slug:"fire-emblem-echoes-shadows-of-valentia", title:"Fire Emblem Echoes: Shadows of Valentia", date:"2017-05-19", score:86, scoreType:"user", hltb:"30h", blurb:"Remake de Gaiden, doublé intégral et direction artistique superbe."},
        {slug:"metroid-samus-returns", title:"Metroid: Samus Returns", date:"2017-09-15", score:88, scoreType:"user", hltb:"11h", blurb:"Le retour de Samus en 2D après 13 ans, remake de l'épisode Game Boy."},
        {slug:"mario-and-luigi-superstar-saga-bowsers-minions", title:"Mario & Luigi: Superstar Saga + Les sbires de Bowser", date:"2017-10-06", score:81, scoreType:"critic", hltb:"15h", blurb:"Le premier Mario & Luigi refait, avec la campagne des sbires en bonus."},
        {slug:"pokemon-ultra-sun-ultra-moon", title:"Pokémon Ultra-Soleil / Ultra-Lune", date:"2017-11-17", score:84, scoreType:"critic", hltb:"35h", blurb:"Version définitive d'Alola, ultime épisode Pokémon de la 3DS."},
        {slug:"warioware-gold", title:"WarioWare Gold", date:"2018-08-03", score:83, scoreType:"critic", hltb:"8h", blurb:"Compilation dorée de 300 micro-jeux, le meilleur du WarioWare."},
        {slug:"persona-q2-new-cinema-labyrinth", title:"Persona Q2: New Cinema Labyrinth", date:"2019-06-04", score:78, scoreType:"critic", hltb:"50h", blurb:"Les héros de Persona 3, 4 et 5 piégés dans un cinéma, adieu en beauté de la 3DS."}
      ]
    },

    gamecube: {
      key: "gamecube",
      name: "GameCube",
      short: "GC",
      color: "#4b3f8f",
      theme: "assets/theme-gamecube.css",
      page: "gamecube.html",
      ready: true,
      games: [
        {slug:"luigis-mansion", title:"Luigi's Mansion", date:"2001-11-18", score:85, scoreType:"user", hltb:"6h", blurb:"Luigi aspire les fantômes d'un manoir hanté, titre de lancement devenu culte."},
        {slug:"star-wars-rogue-squadron-2-rogue-leader", title:"Star Wars Rogue Squadron II: Rogue Leader", date:"2001-11-18", score:87, scoreType:"user", hltb:"6h", blurb:"Vitrine technique du lancement, batailles spatiales spectaculaires de la trilogie originale."},
        {slug:"super-monkey-ball", title:"Super Monkey Ball", date:"2001-11-18", score:87, scoreType:"critic", hltb:"5h", blurb:"Des singes dans des boules, un concept simple et une exigence redoutable."},
        {slug:"tony-hawks-pro-skater-3", title:"Tony Hawk's Pro Skater 3", date:"2001-11-18", score:91, scoreType:"critic", hltb:"6h", blurb:"Le sommet de la série de skate, fluide et jubilatoire, avec le revert."},
        {slug:"wave-race-blue-storm", title:"Wave Race: Blue Storm", date:"2001-11-18", score:80, scoreType:"critic", hltb:"3h", blurb:"Courses de jet-ski à la physique de l'eau impressionnante pour l'époque."},
        {slug:"pikmin", title:"Pikmin", date:"2001-12-02", score:88, scoreType:"user", hltb:"10h", blurb:"Stratégie en temps réel miniature signée Miyamoto, 30 jours pour repartir."},
        {slug:"super-smash-bros-melee", title:"Super Smash Bros. Melee", date:"2001-12-03", score:92, scoreType:"user", hltb:"7h", blurb:"Le jeu de combat le plus vendu de la console, toujours joué en compétition."},
        {slug:"sonic-adventure-2-battle", title:"Sonic Adventure 2: Battle", date:"2002-02-11", score:87, scoreType:"user", hltb:"11h", blurb:"Version enrichie de l'aventure Dreamcast, Chao Garden et mode 2 joueurs inclus."},
        {slug:"resident-evil", title:"Resident Evil", date:"2002-04-30", score:91, scoreType:"user", hltb:"11h", blurb:"Remake somptueux du survival horror fondateur, référence du genre."},
        {slug:"eternal-darkness-sanitys-requiem", title:"Eternal Darkness: Sanity's Requiem", date:"2002-06-24", score:89, scoreType:"user", hltb:"15h", blurb:"Horreur psychologique traversant les siècles, avec ses fameux effets de folie."},
        {slug:"super-monkey-ball-2", title:"Super Monkey Ball 2", date:"2002-08-26", score:87, scoreType:"critic", hltb:"9h", blurb:"Suite plus généreuse, mode histoire et mini-jeux multijoueur mémorables."},
        {slug:"super-mario-sunshine", title:"Super Mario Sunshine", date:"2002-08-26", score:86, scoreType:"user", hltb:"16h", blurb:"Mario et sa pompe J.E.T. nettoient l'île Delfino, vacances ensoleillées."},
        {slug:"animal-crossing", title:"Animal Crossing", date:"2002-09-16", score:85, scoreType:"user", hltb:"30h", blurb:"Vie de village en temps réel, premier épisode sorti en Occident."},
        {slug:"star-fox-adventures", title:"Star Fox Adventures", date:"2002-09-23", score:82, scoreType:"critic", hltb:"15h", blurb:"Dernier jeu de Rare chez Nintendo, aventure à la Zelda avec Fox McCloud."},
        {slug:"timesplitters-2", title:"TimeSplitters 2", date:"2002-10-08", score:88, scoreType:"critic", hltb:"8h", blurb:"FPS à voyages temporels des créateurs de GoldenEye, multijoueur déjanté."},
        {slug:"phantasy-star-online-episode-1-2", title:"Phantasy Star Online Episode I & II", date:"2002-10-29", score:85, scoreType:"critic", hltb:"30h", blurb:"Le RPG en ligne pionnier de Sega, jouable en écran partagé sur GameCube."},
        {slug:"resident-evil-0", title:"Resident Evil 0", date:"2002-11-12", score:83, scoreType:"critic", hltb:"11h", blurb:"Préquelle avec système de duo Rebecca et Billy, sans coffres de rangement."},
        {slug:"metroid-prime", title:"Metroid Prime", date:"2002-11-17", score:91, scoreType:"user", hltb:"14h", blurb:"Passage magistral de Metroid à la première personne, immersion totale sur Tallon IV."},
        {slug:"skies-of-arcadia-legends", title:"Skies of Arcadia Legends", date:"2003-01-27", score:89, scoreType:"user", hltb:"45h", blurb:"Portage enrichi du RPG de pirates du ciel de la Dreamcast."},
        {slug:"zelda-the-wind-waker", title:"The Legend of Zelda: The Wind Waker", date:"2003-03-24", score:90, scoreType:"user", hltb:"26h", blurb:"Navigation en cel-shading intemporel sur un océan sans fin."},
        {slug:"ikaruga", title:"Ikaruga", date:"2003-04-15", score:88, scoreType:"user", hltb:"2h", blurb:"Shoot'em up de Treasure basé sur la polarité noir/blanc, pur et exigeant."},
        {slug:"mario-golf-toadstool-tour", title:"Mario Golf: Toadstool Tour", date:"2003-07-28", score:81, scoreType:"critic", hltb:"12h", blurb:"Golf arcade accessible et profond avec tout le casting du Royaume Champignon."},
        {slug:"f-zero-gx", title:"F-Zero GX", date:"2003-08-25", score:89, scoreType:"user", hltb:"8h", blurb:"Course futuriste vertigineuse développée par Sega, d'une difficulté légendaire."},
        {slug:"soulcalibur-2", title:"Soulcalibur II", date:"2003-08-27", score:89, scoreType:"user", hltb:"6h", blurb:"Combat à l'arme blanche au sommet, avec Link en invité exclusif."},
        {slug:"the-simpsons-hit-and-run", title:"The Simpsons: Hit & Run", date:"2003-09-16", score:89, scoreType:"user", hltb:"12h", blurb:"GTA parodique dans Springfield, devenu culte auprès de toute une génération."},
        {slug:"viewtiful-joe", title:"Viewtiful Joe", date:"2003-10-07", score:87, scoreType:"user", hltb:"7h", blurb:"Beat'em up stylisé de Capcom où Joe ralentit et accélère le temps."},
        {slug:"ssx-3", title:"SSX 3", date:"2003-10-21", score:92, scoreType:"critic", hltb:"10h", blurb:"Snowboard arcade sur une montagne entière, sommet de la série d'EA."},
        {slug:"mario-kart-double-dash", title:"Mario Kart: Double Dash!!", date:"2003-11-17", score:88, scoreType:"user", hltb:"4h", blurb:"Deux pilotes par kart et objets spéciaux, l'épisode le plus coopératif."},
        {slug:"prince-of-persia-the-sands-of-time", title:"Prince of Persia: The Sands of Time", date:"2003-11-18", score:92, scoreType:"critic", hltb:"8h", blurb:"Renaissance acrobatique de la série, avec la dague qui remonte le temps."},
        {slug:"beyond-good-and-evil", title:"Beyond Good & Evil", date:"2003-12-11", score:90, scoreType:"user", hltb:"10h", blurb:"Aventure de Michel Ancel portée par la reporter Jade, culte malgré son échec commercial."},
        {slug:"final-fantasy-crystal-chronicles", title:"Final Fantasy Crystal Chronicles", date:"2004-02-09", score:80, scoreType:"critic", hltb:"25h", blurb:"Action-RPG coopératif jouable à quatre via les câbles Game Boy Advance."},
        {slug:"metal-gear-solid-the-twin-snakes", title:"Metal Gear Solid: The Twin Snakes", date:"2004-03-09", score:88, scoreType:"user", hltb:"12h", blurb:"Remake du premier Metal Gear Solid avec le gameplay de MGS2."},
        {slug:"pokemon-colosseum", title:"Pokémon Colosseum", date:"2004-03-22", score:84, scoreType:"user", hltb:"25h", blurb:"RPG Pokémon sur console de salon où l'on vole les Pokémon Obscurs."},
        {slug:"zelda-four-swords-adventures", title:"The Legend of Zelda: Four Swords Adventures", date:"2004-06-07", score:86, scoreType:"critic", hltb:"15h", blurb:"Zelda coopératif à quatre Link, connecté aux Game Boy Advance."},
        {slug:"tales-of-symphonia", title:"Tales of Symphonia", date:"2004-07-13", score:89, scoreType:"user", hltb:"45h", blurb:"RPG d'action au scénario généreux, épisode le plus aimé de la série Tales."},
        {slug:"pikmin-2", title:"Pikmin 2", date:"2004-08-30", score:90, scoreType:"user", hltb:"20h", blurb:"Suite sans limite de temps, grottes, trésors et deux capitaines."},
        {slug:"paper-mario-the-thousand-year-door", title:"Paper Mario: The Thousand-Year Door", date:"2004-10-11", score:91, scoreType:"user", hltb:"35h", blurb:"RPG en papier à l'écriture hilarante, souvent cité comme le meilleur Paper Mario."},
        {slug:"mario-power-tennis", title:"Mario Power Tennis", date:"2004-11-08", score:81, scoreType:"critic", hltb:"5h", blurb:"Tennis arcade avec coups spéciaux spectaculaires et courts à pièges."},
        {slug:"metroid-prime-2-echoes", title:"Metroid Prime 2: Echoes", date:"2004-11-15", score:88, scoreType:"user", hltb:"20h", blurb:"Suite plus sombre entre monde lumineux et monde des ténèbres."},
        {slug:"baten-kaitos-eternal-wings", title:"Baten Kaitos: Eternal Wings and the Lost Ocean", date:"2004-11-16", score:80, scoreType:"critic", hltb:"55h", blurb:"RPG à cartes aux décors peints à la main, dans un monde d'îles célestes."},
        {slug:"viewtiful-joe-2", title:"Viewtiful Joe 2", date:"2004-11-18", score:86, scoreType:"critic", hltb:"8h", blurb:"Suite directe avec Silvia jouable et un nouveau pouvoir de zoom."},
        {slug:"resident-evil-4", title:"Resident Evil 4", date:"2005-01-11", score:93, scoreType:"user", hltb:"16h", blurb:"Révolution du TPS avec sa caméra à l'épaule, chef-d'oeuvre absolu de Capcom."},
        {slug:"donkey-kong-jungle-beat", title:"Donkey Kong Jungle Beat", date:"2005-03-14", score:81, scoreType:"critic", hltb:"5h", blurb:"Plateforme rythmique qui se joue entièrement aux bongos DK."},
        {slug:"killer7", title:"Killer7", date:"2005-07-07", score:84, scoreType:"user", hltb:"15h", blurb:"Thriller stylisé et radical de Suda51, sept tueurs dans un même corps."},
        {slug:"pokemon-xd-gale-of-darkness", title:"Pokémon XD: Gale of Darkness", date:"2005-10-03", score:80, scoreType:"user", hltb:"30h", blurb:"Suite de Colosseum autour d'un Lugia Obscur réputé impossible à purifier."},
        {slug:"fire-emblem-path-of-radiance", title:"Fire Emblem: Path of Radiance", date:"2005-10-17", score:90, scoreType:"user", hltb:"30h", blurb:"Premier Fire Emblem en 3D, début de l'histoire d'Ike et des mercenaires de Greil."},
        {slug:"super-mario-strikers", title:"Super Mario Strikers", date:"2005-12-05", score:76, scoreType:"critic", hltb:"6h", blurb:"Football arcade brutal et nerveux, sans arbitre ni pitié."},
        {slug:"chibi-robo", title:"Chibi-Robo!", date:"2006-02-06", score:77, scoreType:"critic", hltb:"14h", blurb:"Petit robot ménager qui répare le quotidien d'une famille, attachant et original."},
        {slug:"baten-kaitos-origins", title:"Baten Kaitos Origins", date:"2006-09-25", score:84, scoreType:"critic", hltb:"40h", blurb:"Préquelle au système de cartes affiné, jamais sortie en Europe."},
        {slug:"zelda-twilight-princess", title:"The Legend of Zelda: Twilight Princess", date:"2006-12-11", score:90, scoreType:"user", hltb:"34h", blurb:"Ultime jeu GameCube, Link loup et crépuscule pour un adieu épique."}
      ]
    },

    ps2: {
      key: "ps2",
      name: "PlayStation 2",
      short: "PS2",
      color: "#4a5fc1",
      theme: "assets/theme-ps2.css",
      page: "ps2.html",
      ready: true,
      games: [
        {slug:"ssx", title:"SSX", date:"2000-10-25", score:93, scoreType:"critic", hltb:"8h", blurb:"Snowboard arcade survolté du lancement, naissance d'une série culte."},
        {slug:"onimusha-warlords", title:"Onimusha: Warlords", date:"2001-03-13", score:86, scoreType:"critic", hltb:"6h", blurb:"Samouraïs contre démons dans un Japon féodal façon Resident Evil."},
        {slug:"twisted-metal-black", title:"Twisted Metal: Black", date:"2001-06-18", score:91, scoreType:"critic", hltb:"8h", blurb:"Combat motorisé sombre et nerveux, sommet de la série."},
        {slug:"gran-turismo-3-a-spec", title:"Gran Turismo 3: A-Spec", date:"2001-07-09", score:95, scoreType:"critic", hltb:"30h", blurb:"La vitrine technique de la PS2, simulation automobile de référence."},
        {slug:"klonoa-2-lunateas-veil", title:"Klonoa 2: Lunatea's Veil", date:"2001-07-24", score:91, scoreType:"critic", hltb:"8h", blurb:"Plateforme 2.5D onirique et mélancolique, injustement méconnue."},
        {slug:"silent-hill-2", title:"Silent Hill 2", date:"2001-09-24", score:92, scoreType:"user", hltb:"8h", blurb:"Descente psychologique dans la brume, référence absolue de l'horreur."},
        {slug:"ico", title:"Ico", date:"2001-09-24", score:90, scoreType:"user", hltb:"6h", blurb:"Un garçon, une princesse et un château : la poésie selon Fumito Ueda."},
        {slug:"devil-may-cry", title:"Devil May Cry", date:"2001-10-16", score:88, scoreType:"user", hltb:"8h", blurb:"Dante invente le jeu d'action stylé, pistolets et épée démoniaque en main."},
        {slug:"grand-theft-auto-3", title:"Grand Theft Auto III", date:"2001-10-22", score:87, scoreType:"user", hltb:"16h", blurb:"Liberty City en monde ouvert 3D, le jeu qui a tout changé."},
        {slug:"metal-gear-solid-2-sons-of-liberty", title:"Metal Gear Solid 2: Sons of Liberty", date:"2001-11-13", score:89, scoreType:"user", hltb:"11h", blurb:"Infiltration virtuose et scénario vertigineux signés Hideo Kojima."},
        {slug:"jak-and-daxter-the-precursor-legacy", title:"Jak and Daxter: The Precursor Legacy", date:"2001-12-03", score:87, scoreType:"user", hltb:"10h", blurb:"Plateforme sans temps de chargement de Naughty Dog, monde continu."},
        {slug:"final-fantasy-10", title:"Final Fantasy X", date:"2001-12-17", score:89, scoreType:"user", hltb:"45h", blurb:"Le voyage de Tidus et Yuna à Spira, premier Final Fantasy doublé."},
        {slug:"kingdom-hearts", title:"Kingdom Hearts", date:"2002-09-16", score:88, scoreType:"user", hltb:"30h", blurb:"La rencontre improbable de Disney et Final Fantasy, devenue légendaire."},
        {slug:"sly-cooper-and-the-thievius-raccoonus", title:"Sly Cooper and the Thievius Raccoonus", date:"2002-09-23", score:86, scoreType:"critic", hltb:"7h", blurb:"Cambriolages en cel-shading avec le raton laveur le plus classe du genre."},
        {slug:"gta-vice-city", title:"Grand Theft Auto: Vice City", date:"2002-10-27", score:87, scoreType:"user", hltb:"18h", blurb:"Miami années 80, néons et radio culte : le GTA le plus stylé."},
        {slug:"ratchet-and-clank", title:"Ratchet & Clank", date:"2002-11-04", score:89, scoreType:"user", hltb:"11h", blurb:"Duo lombax-robot et arsenal délirant, début d'une grande série."},
        {slug:"dark-cloud-2", title:"Dark Cloud 2", date:"2003-02-17", score:87, scoreType:"critic", hltb:"45h", blurb:"Action-RPG de Level-5 mêlant donjons, photos, inventions et reconstruction."},
        {slug:"zone-of-the-enders-the-2nd-runner", title:"Zone of the Enders: The 2nd Runner", date:"2003-03-11", score:84, scoreType:"critic", hltb:"6h", blurb:"Combats de mechas fulgurants produits par Kojima, pur concentré d'adrénaline."},
        {slug:"silent-hill-3", title:"Silent Hill 3", date:"2003-08-06", score:85, scoreType:"critic", hltb:"7h", blurb:"Suite directe du premier épisode, portée par Heather et une ambiance suffocante."},
        {slug:"disgaea-hour-of-darkness", title:"Disgaea: Hour of Darkness", date:"2003-08-27", score:89, scoreType:"user", hltb:"45h", blurb:"Tactical-RPG parodique aux niveaux 9999 et à l'humour démoniaque."},
        {slug:"jak-2", title:"Jak II", date:"2003-10-14", score:87, scoreType:"critic", hltb:"15h", blurb:"Virage sombre et monde ouvert pour la suite de Naughty Dog."},
        {slug:"ratchet-and-clank-going-commando", title:"Ratchet & Clank: Going Commando", date:"2003-11-11", score:90, scoreType:"user", hltb:"15h", blurb:"Suite plus grande et mieux armée, la formule Ratchet à maturité."},
        {slug:"final-fantasy-10-2", title:"Final Fantasy X-2", date:"2003-11-18", score:85, scoreType:"critic", hltb:"30h", blurb:"Yuna, Rikku et Paine reprennent Spira sur un ton pop et léger."},
        {slug:"burnout-3-takedown", title:"Burnout 3: Takedown", date:"2004-09-07", score:89, scoreType:"user", hltb:"15h", blurb:"Courses à crashs spectaculaires, l'arcade à son sommet absolu."},
        {slug:"sly-2-band-of-thieves", title:"Sly 2: Band of Thieves", date:"2004-09-14", score:88, scoreType:"critic", hltb:"14h", blurb:"Braquages en équipe et ville ouverte, le meilleur épisode de la bande."},
        {slug:"katamari-damacy", title:"Katamari Damacy", date:"2004-09-22", score:88, scoreType:"user", hltb:"5h", blurb:"Rouler une boule qui agglutine le monde entier, absurde et génial."},
        {slug:"shadow-hearts-covenant", title:"Shadow Hearts: Covenant", date:"2004-09-27", score:85, scoreType:"critic", hltb:"40h", blurb:"RPG gothique dans l'Europe de 1915, avec sa fameuse Judgment Ring."},
        {slug:"shin-megami-tensei-nocturne", title:"Shin Megami Tensei: Nocturne", date:"2004-10-12", score:90, scoreType:"user", hltb:"50h", blurb:"Tokyo détruit et renaissance du monde, le SMT le plus culte."},
        {slug:"ace-combat-5-the-unsung-war", title:"Ace Combat 5: The Unsung War", date:"2004-10-25", score:84, scoreType:"critic", hltb:"12h", blurb:"Dogfights spectaculaires et escadron attachant, l'apogée de la série."},
        {slug:"gta-san-andreas", title:"Grand Theft Auto: San Andreas", date:"2004-10-26", score:90, scoreType:"user", hltb:"31h", blurb:"Trois villes, un État entier : le GTA le plus vaste et le plus aimé."},
        {slug:"ratchet-and-clank-up-your-arsenal", title:"Ratchet & Clank: Up Your Arsenal", date:"2004-11-02", score:91, scoreType:"critic", hltb:"12h", blurb:"Troisième épisode surarmé, avec le Dr Nefarious et un multi en ligne."},
        {slug:"jak-3", title:"Jak 3", date:"2004-11-09", score:84, scoreType:"critic", hltb:"12h", blurb:"Conclusion de la trilogie entre désert et ville, buggies à l'appui."},
        {slug:"metal-gear-solid-3-snake-eater", title:"Metal Gear Solid 3: Snake Eater", date:"2004-11-17", score:93, scoreType:"user", hltb:"16h", blurb:"Survie en jungle pendant la guerre froide, souvent cité comme le meilleur MGS."},
        {slug:"gran-turismo-4", title:"Gran Turismo 4", date:"2005-02-22", score:89, scoreType:"critic", hltb:"40h", blurb:"700 voitures et le Nürburgring, l'encyclopédie automobile de la PS2."},
        {slug:"tekken-5", title:"Tekken 5", date:"2005-02-24", score:88, scoreType:"critic", hltb:"6h", blurb:"Retour en forme de la baston 3D, avec les Tekken arcade en bonus."},
        {slug:"devil-may-cry-3-dantes-awakening", title:"Devil May Cry 3: Dante's Awakening", date:"2005-03-01", score:89, scoreType:"user", hltb:"12h", blurb:"Dante jeune et arrogant, action au style exigeant et jubilatoire."},
        {slug:"god-of-war", title:"God of War", date:"2005-03-22", score:91, scoreType:"user", hltb:"9h", blurb:"La vengeance de Kratos contre l'Olympe, brutale et mise en scène."},
        {slug:"shadow-of-the-colossus", title:"Shadow of the Colossus", date:"2005-10-18", score:92, scoreType:"user", hltb:"8h", blurb:"Seize colosses dans une terre interdite, chef-d'oeuvre de Fumito Ueda."},
        {slug:"guitar-hero", title:"Guitar Hero", date:"2005-11-08", score:91, scoreType:"critic", hltb:"6h", blurb:"La guitare en plastique qui a déclenché un phénomène mondial."},
        {slug:"dragon-quest-8-journey-of-the-cursed-king", title:"Dragon Quest VIII: L'Odyssée du Roi Maudit", date:"2005-11-15", score:91, scoreType:"user", hltb:"60h", blurb:"Le Dragon Quest en cel-shading grandiose, premier arrivé en Europe."},
        {slug:"kingdom-hearts-2", title:"Kingdom Hearts II", date:"2006-03-28", score:89, scoreType:"user", hltb:"35h", blurb:"Sora revient dans une aventure plus ample au système de combat affiné."},
        {slug:"okami", title:"Ōkami", date:"2006-09-19", score:91, scoreType:"user", hltb:"30h", blurb:"La déesse Amaterasu repeint le monde au pinceau céleste, estampe jouable."},
        {slug:"god-hand", title:"God Hand", date:"2006-10-10", score:89, scoreType:"user", hltb:"12h", blurb:"Beat'em up délirant et ultra-exigeant de Clover, devenu culte."},
        {slug:"bully", title:"Bully", date:"2006-10-17", score:86, scoreType:"user", hltb:"17h", blurb:"Rockstar au pensionnat : chahut, cours et petites magouilles."},
        {slug:"final-fantasy-12", title:"Final Fantasy XII", date:"2006-10-31", score:84, scoreType:"user", hltb:"60h", blurb:"Ivalice en monde semi-ouvert et combats au gambit, épisode ambitieux."},
        {slug:"rogue-galaxy", title:"Rogue Galaxy", date:"2007-01-30", score:82, scoreType:"critic", hltb:"45h", blurb:"Space opera d'action-RPG de Level-5, pirates et planètes exotiques."},
        {slug:"god-of-war-2", title:"God of War II", date:"2007-03-13", score:91, scoreType:"user", hltb:"11h", blurb:"Kratos défie les Titans, chant du cygne spectaculaire de la console."},
        {slug:"odin-sphere", title:"Odin Sphere", date:"2007-05-22", score:83, scoreType:"critic", hltb:"25h", blurb:"Cinq destins croisés en 2D somptueuse signée Vanillaware."},
        {slug:"persona-3-fes", title:"Persona 3 FES", date:"2008-04-22", score:90, scoreType:"user", hltb:"70h", blurb:"Lycée le jour, Tartare la nuit : version enrichie du RPG qui a réinventé Persona."},
        {slug:"persona-4", title:"Persona 4", date:"2008-12-09", score:92, scoreType:"user", hltb:"70h", blurb:"Enquête surnaturelle à Inaba, ultime grand RPG de la PlayStation 2."}
      ]
    },

    jrpg: {
      key: "jrpg",
      name: "JRPG",
      short: "JRPG",
      color: "#c14a6b",
      theme: "assets/theme-jrpg.css",
      page: "jrpg.html",
      ready: true,
      games: [
        {slug:"dark-cloud", title:"Dark Cloud (PS2)", date:"2001-05-29", score:80, scoreType:"critic", hltb:"25h", blurb:"Donjons et reconstruction de villages, premier RPG maison de Level-5."},
        {slug:"shadow-hearts", title:"Shadow Hearts (PS2)", date:"2001-12-11", score:73, scoreType:"critic", hltb:"35h", blurb:"Horreur lovecraftienne et Judgment Ring, l'anti-RPG classique."},
        {slug:"final-fantasy-10", title:"Final Fantasy X (PS2)", date:"2001-12-17", score:89, scoreType:"user", hltb:"45h", blurb:"Le voyage de Tidus et Yuna à Spira, premier Final Fantasy doublé."},
        {slug:"kingdom-hearts", title:"Kingdom Hearts (PS2)", date:"2002-09-16", score:88, scoreType:"user", hltb:"30h", blurb:"La rencontre improbable de Disney et Final Fantasy, devenue légendaire."},
        {slug:"wild-arms-3", title:"Wild Arms 3 (PS2)", date:"2002-10-15", score:79, scoreType:"critic", hltb:"35h", blurb:"Western fantastique en cel-shading, chevauchées et gardiens anciens."},
        {slug:"suikoden-3", title:"Suikoden III (PS2)", date:"2002-10-24", score:81, scoreType:"critic", hltb:"35h", blurb:"Trois points de vue croisés et 108 étoiles du destin à recruter."},
        {slug:"skies-of-arcadia-legends", title:"Skies of Arcadia Legends (GC)", date:"2003-01-27", score:89, scoreType:"user", hltb:"45h", blurb:"Portage enrichi du RPG de pirates du ciel de la Dreamcast."},
        {slug:"breath-of-fire-dragon-quarter", title:"Breath of Fire: Dragon Quarter (PS2)", date:"2003-02-14", score:78, scoreType:"critic", hltb:"20h", blurb:"Épisode radical en sous-sol, compteur dragon et recommencements assumés."},
        {slug:"dark-cloud-2", title:"Dark Cloud 2 (PS2)", date:"2003-02-17", score:87, scoreType:"critic", hltb:"45h", blurb:"Action-RPG mêlant donjons, photos, inventions et reconstruction."},
        {slug:"xenosaga-episode-1", title:"Xenosaga Episode I (PS2)", date:"2003-02-25", score:83, scoreType:"critic", hltb:"40h", blurb:"Space opera philosophique très narratif, début de la trilogie de Monolith."},
        {slug:"disgaea-hour-of-darkness", title:"Disgaea: Hour of Darkness (PS2)", date:"2003-08-27", score:89, scoreType:"user", hltb:"45h", blurb:"Tactical-RPG parodique aux niveaux 9999 et à l'humour démoniaque."},
        {slug:"final-fantasy-10-2", title:"Final Fantasy X-2 (PS2)", date:"2003-11-18", score:85, scoreType:"critic", hltb:"30h", blurb:"Yuna, Rikku et Paine reprennent Spira sur un ton pop et léger."},
        {slug:"final-fantasy-crystal-chronicles", title:"Final Fantasy Crystal Chronicles (GC)", date:"2004-02-09", score:80, scoreType:"critic", hltb:"25h", blurb:"Action-RPG coopératif jouable à quatre via les câbles Game Boy Advance."},
        {slug:"pokemon-colosseum", title:"Pokémon Colosseum (GC)", date:"2004-03-22", score:84, scoreType:"user", hltb:"25h", blurb:"RPG Pokémon de salon où l'on vole les Pokémon Obscurs."},
        {slug:"tales-of-symphonia", title:"Tales of Symphonia (GC)", date:"2004-07-13", score:89, scoreType:"user", hltb:"45h", blurb:"RPG d'action au scénario généreux, épisode le plus aimé des Tales."},
        {slug:"star-ocean-till-the-end-of-time", title:"Star Ocean: Till the End of Time (PS2)", date:"2004-08-31", score:80, scoreType:"critic", hltb:"40h", blurb:"Science-fantasy aux combats en temps réel, avec un twist resté fameux."},
        {slug:"shadow-hearts-covenant", title:"Shadow Hearts: Covenant (PS2)", date:"2004-09-27", score:85, scoreType:"critic", hltb:"40h", blurb:"RPG gothique dans l'Europe de 1915, sommet de la série."},
        {slug:"paper-mario-the-thousand-year-door", title:"Paper Mario: The Thousand-Year Door (GC)", date:"2004-10-11", score:91, scoreType:"user", hltb:"35h", blurb:"RPG en papier à l'écriture hilarante, souvent cité comme le meilleur Paper Mario."},
        {slug:"shin-megami-tensei-nocturne", title:"Shin Megami Tensei: Nocturne (PS2)", date:"2004-10-12", score:90, scoreType:"user", hltb:"50h", blurb:"Tokyo détruit et renaissance du monde, le SMT le plus culte."},
        {slug:"baten-kaitos-eternal-wings", title:"Baten Kaitos: Eternal Wings and the Lost Ocean (GC)", date:"2004-11-16", score:80, scoreType:"critic", hltb:"55h", blurb:"RPG à cartes aux décors peints à la main, dans un monde d'îles célestes."},
        {slug:"digital-devil-saga", title:"Shin Megami Tensei: Digital Devil Saga (PS2)", date:"2005-04-05", score:84, scoreType:"critic", hltb:"30h", blurb:"Spin-off SMT au tour par tour où les héros dévorent leurs ennemis."},
        {slug:"radiata-stories", title:"Radiata Stories (PS2)", date:"2005-09-06", score:77, scoreType:"critic", hltb:"40h", blurb:"RPG léger aux 177 personnages recrutables et au choix déchirant."},
        {slug:"pokemon-xd-gale-of-darkness", title:"Pokémon XD: Gale of Darkness (GC)", date:"2005-10-03", score:80, scoreType:"user", hltb:"30h", blurb:"Suite de Colosseum autour d'un Lugia Obscur réputé impossible à purifier."},
        {slug:"digital-devil-saga-2", title:"Shin Megami Tensei: Digital Devil Saga 2 (PS2)", date:"2005-10-04", score:84, scoreType:"critic", hltb:"30h", blurb:"Conclusion du diptyque, du Junkyard vers le monde réel."},
        {slug:"fire-emblem-path-of-radiance", title:"Fire Emblem: Path of Radiance (GC)", date:"2005-10-17", score:90, scoreType:"user", hltb:"30h", blurb:"Premier Fire Emblem en 3D, début de l'histoire d'Ike et des mercenaires de Greil."},
        {slug:"dragon-quest-8", title:"Dragon Quest VIII: L'Odyssée du Roi Maudit (PS2)", date:"2005-11-15", score:91, scoreType:"user", hltb:"60h", blurb:"Le Dragon Quest en cel-shading grandiose, premier arrivé en Europe."},
        {slug:"suikoden-5", title:"Suikoden V (PS2)", date:"2006-03-21", score:78, scoreType:"critic", hltb:"45h", blurb:"Retour aux sources pour la saga des 108 étoiles du destin."},
        {slug:"kingdom-hearts-2", title:"Kingdom Hearts II (PS2)", date:"2006-03-28", score:89, scoreType:"user", hltb:"35h", blurb:"Sora revient dans une aventure plus ample au système de combat affiné."},
        {slug:"disgaea-2", title:"Disgaea 2: Cursed Memories (PS2)", date:"2006-08-29", score:84, scoreType:"critic", hltb:"45h", blurb:"Nouvelle plongée dans le Netherworld, toujours plus de niveaux absurdes."},
        {slug:"xenosaga-episode-3", title:"Xenosaga Episode III (PS2)", date:"2006-08-29", score:81, scoreType:"critic", hltb:"35h", blurb:"Conclusion resserrée et spectaculaire de la trilogie KOS-MOS."},
        {slug:"baten-kaitos-origins", title:"Baten Kaitos Origins (GC)", date:"2006-09-25", score:84, scoreType:"critic", hltb:"40h", blurb:"Préquelle au système de cartes affiné, jamais sortie en Europe."},
        {slug:"valkyrie-profile-2-silmeria", title:"Valkyrie Profile 2: Silmeria (PS2)", date:"2006-09-26", score:84, scoreType:"critic", hltb:"40h", blurb:"Silmeria et ses einherjar dans un système de combat d'orfèvre."},
        {slug:"tales-of-the-abyss", title:"Tales of the Abyss (PS2)", date:"2006-10-10", score:78, scoreType:"critic", hltb:"45h", blurb:"Luke apprend à exister au-delà de sa réplique, un Tales majeur."},
        {slug:"final-fantasy-12", title:"Final Fantasy XII (PS2)", date:"2006-10-31", score:84, scoreType:"user", hltb:"60h", blurb:"Ivalice en monde semi-ouvert et combats au gambit, épisode ambitieux."},
        {slug:"final-fantasy-3", title:"Final Fantasy III (DS)", date:"2006-11-14", score:77, scoreType:"critic", hltb:"30h", blurb:"Remake 3D du seul Final Fantasy alors jamais sorti du Japon."},
        {slug:"rogue-galaxy", title:"Rogue Galaxy (PS2)", date:"2007-01-30", score:82, scoreType:"critic", hltb:"45h", blurb:"Space opera d'action-RPG de Level-5, pirates et planètes exotiques."},
        {slug:"super-paper-mario", title:"Super Paper Mario (Wii)", date:"2007-04-09", score:85, scoreType:"critic", hltb:"16h", blurb:"Mario bascule entre 2D et 3D dans un RPG-plateforme bavard et malin."},
        {slug:"pokemon-diamond-pearl", title:"Pokémon Diamant / Perle (DS)", date:"2007-04-22", score:85, scoreType:"user", hltb:"40h", blurb:"Quatrième génération à Sinnoh, avec les échanges Wi-Fi mondiaux."},
        {slug:"odin-sphere", title:"Odin Sphere (PS2)", date:"2007-05-22", score:83, scoreType:"critic", hltb:"25h", blurb:"Cinq destins croisés en 2D somptueuse signée Vanillaware."},
        {slug:"fire-emblem-radiant-dawn", title:"Fire Emblem: Radiant Dawn (Wii)", date:"2007-11-05", score:78, scoreType:"critic", hltb:"35h", blurb:"Suite directe de Path of Radiance, exigeante et riche en points de vue."},
        {slug:"dragon-quest-monsters-joker", title:"Dragon Quest Monsters: Joker (DS)", date:"2007-11-06", score:77, scoreType:"critic", hltb:"30h", blurb:"Élevage et synthèse de monstres Dragon Quest en 3D."},
        {slug:"the-world-ends-with-you", title:"The World Ends with You (DS)", date:"2008-04-22", score:90, scoreType:"user", hltb:"20h", blurb:"RPG d'action ultra-stylé dans Shibuya, combats sur les deux écrans."},
        {slug:"persona-3-fes", title:"Persona 3 FES (PS2)", date:"2008-04-22", score:90, scoreType:"user", hltb:"70h", blurb:"Lycée le jour, Tartare la nuit : le RPG qui a réinventé Persona."},
        {slug:"final-fantasy-tactics-a2", title:"Final Fantasy Tactics A2: Grimoire of the Rift (DS)", date:"2008-06-24", score:80, scoreType:"critic", hltb:"40h", blurb:"Tactical-RPG généreux dans le monde d'Ivalice."},
        {slug:"final-fantasy-4-ds", title:"Final Fantasy IV (DS)", date:"2008-07-22", score:85, scoreType:"critic", hltb:"25h", blurb:"Remake 3D du drame de Cecil, plus difficile et entièrement doublé."},
        {slug:"dragon-quest-4", title:"Dragon Quest IV: L'Épopée des Élus (DS)", date:"2008-09-16", score:80, scoreType:"critic", hltb:"30h", blurb:"Remake du classique NES raconté en chapitres, un par héros."},
        {slug:"eternal-sonata", title:"Eternal Sonata (PS3)", date:"2008-10-21", score:80, scoreType:"critic", hltb:"30h", blurb:"RPG musical rêvé par Chopin mourant, mélancolique et coloré."},
        {slug:"valkyria-chronicles", title:"Valkyria Chronicles (PS3)", date:"2008-11-04", score:89, scoreType:"user", hltb:"30h", blurb:"Tactique en aquarelle dans une Europe alternative en guerre."},
        {slug:"chrono-trigger", title:"Chrono Trigger (DS)", date:"2008-11-25", score:91, scoreType:"user", hltb:"23h", blurb:"Le voyage temporel légendaire de la SNES, enfin portable."},
        {slug:"persona-4", title:"Persona 4 (PS2)", date:"2008-12-09", score:92, scoreType:"user", hltb:"70h", blurb:"Enquête surnaturelle à Inaba, ultime grand RPG de la PlayStation 2."},
        {slug:"fire-emblem-shadow-dragon", title:"Fire Emblem: Shadow Dragon (DS)", date:"2009-02-16", score:81, scoreType:"critic", hltb:"20h", blurb:"Remake du tout premier Fire Emblem, avec Marth."},
        {slug:"dragon-quest-5", title:"Dragon Quest V: La Fiancée Céleste (DS)", date:"2009-02-17", score:89, scoreType:"user", hltb:"30h", blurb:"Une vie entière racontée, souvent cité comme le sommet de la saga."},
        {slug:"pokemon-platinum", title:"Pokémon Platine (DS)", date:"2009-03-22", score:88, scoreType:"user", hltb:"40h", blurb:"Version définitive de Sinnoh, avec le Monde Distorsion."},
        {slug:"smt-devil-survivor", title:"Shin Megami Tensei: Devil Survivor (DS)", date:"2009-06-23", score:84, scoreType:"critic", hltb:"30h", blurb:"Tokyo bouclé pendant sept jours, tactique et enchères de démons."},
        {slug:"mario-and-luigi-bowsers-inside-story", title:"Mario & Luigi: Voyage au centre de Bowser (DS)", date:"2009-09-14", score:89, scoreType:"user", hltb:"25h", blurb:"Mario et Luigi explorent l'intérieur de Bowser, sommet de la série."},
        {slug:"demons-souls", title:"Demon's Souls (PS3)", date:"2009-10-06", score:92, scoreType:"user", hltb:"30h", blurb:"L'acte fondateur de From Software, Boletaria et ses âmes."},
        {slug:"pokemon-mystery-dungeon-explorers-of-sky", title:"Pokémon Donjon Mystère: Explorateurs du Ciel (DS)", date:"2009-10-12", score:86, scoreType:"user", hltb:"35h", blurb:"Version ultime d'Explorateurs, l'histoire Pokémon la plus émouvante."},
        {slug:"final-fantasy-13", title:"Final Fantasy XIII (PS3)", date:"2010-03-09", score:83, scoreType:"critic", hltb:"45h", blurb:"Odyssée linéaire mais spectaculaire à Cocoon, système Paradigm au cordeau."},
        {slug:"pokemon-heartgold-soulsilver", title:"Pokémon HeartGold / SoulSilver (DS)", date:"2010-03-14", score:90, scoreType:"user", hltb:"40h", blurb:"Remake de la deuxième génération, Johto et Kanto réunis."},
        {slug:"smt-strange-journey", title:"Shin Megami Tensei: Strange Journey (DS)", date:"2010-03-23", score:80, scoreType:"critic", hltb:"40h", blurb:"Expédition SMT pure et dure en Antarctique, sombre et fascinante."},
        {slug:"nier", title:"Nier (PS3)", date:"2010-04-27", score:88, scoreType:"user", hltb:"20h", blurb:"Récit déchirant et musiques inoubliables, culte malgré ses rugosités."},
        {slug:"dragon-quest-9", title:"Dragon Quest IX: Les Sentinelles du Firmament (DS)", date:"2010-07-11", score:85, scoreType:"user", hltb:"40h", blurb:"Épisode pensé pour le jeu en groupe, au contenu immense."},
        {slug:"golden-sun-dark-dawn", title:"Golden Sun: Dark Dawn (DS)", date:"2010-11-29", score:79, scoreType:"critic", hltb:"30h", blurb:"La saga Psynergie revient une génération plus tard."},
        {slug:"dragon-quest-6", title:"Dragon Quest VI: Le Royaume des Songes (DS)", date:"2011-02-14", score:78, scoreType:"critic", hltb:"35h", blurb:"Remake du dernier volet de la trilogie céleste, entre rêve et réalité."},
        {slug:"radiant-historia", title:"Radiant Historia (DS)", date:"2011-02-22", score:88, scoreType:"user", hltb:"30h", blurb:"RPG à voyages temporels entre deux lignes d'histoire parallèles."},
        {slug:"pokemon-black-white", title:"Pokémon Noir / Blanc (DS)", date:"2011-03-06", score:82, scoreType:"user", hltb:"32h", blurb:"Cinquième génération à Unys, avec uniquement de nouveaux Pokémon."},
        {slug:"disgaea-4", title:"Disgaea 4: A Promise Unforgotten (PS3)", date:"2011-09-06", score:80, scoreType:"critic", hltb:"45h", blurb:"Sardines, révolution et grinding infini dans le Netherworld en HD."},
        {slug:"dark-souls", title:"Dark Souls (PS3)", date:"2011-10-04", score:90, scoreType:"user", hltb:"40h", blurb:"Lordran interconnecté et implacable, le RPG d'action qui a fait école."},
        {slug:"final-fantasy-13-2", title:"Final Fantasy XIII-2 (PS3)", date:"2012-01-31", score:79, scoreType:"critic", hltb:"40h", blurb:"Suite à voyages temporels qui corrige la linéarité de XIII."},
        {slug:"tales-of-graces-f", title:"Tales of Graces f (PS3)", date:"2012-03-13", score:77, scoreType:"critic", hltb:"40h", blurb:"Le système de combat le plus affûté de la série Tales."},
        {slug:"xenoblade-chronicles", title:"Xenoblade Chronicles (Wii)", date:"2012-04-06", score:90, scoreType:"user", hltb:"60h", blurb:"Monde ouvert porté par deux titans, l'immense RPG de Monolith Soft."},
        {slug:"the-last-story", title:"The Last Story (Wii)", date:"2012-08-14", score:80, scoreType:"critic", hltb:"20h", blurb:"Le RPG crépusculaire de Sakaguchi sur Wii, intime et resserré."},
        {slug:"pokemon-black-2-white-2", title:"Pokémon Noir 2 / Blanc 2 (DS)", date:"2012-10-07", score:84, scoreType:"user", hltb:"35h", blurb:"Suites directes inédites, retour à Unys deux ans après."},
        {slug:"ni-no-kuni-wrath-of-the-white-witch", title:"Ni no Kuni: Wrath of the White Witch (PS3)", date:"2013-01-22", score:85, scoreType:"user", hltb:"45h", blurb:"Conte animé par le studio Ghibli, féérique et généreux."},
        {slug:"fire-emblem-awakening", title:"Fire Emblem: Awakening (3DS)", date:"2013-02-04", score:89, scoreType:"user", hltb:"25h", blurb:"L'épisode qui a sauvé la série, avec mariages et enfants entre unités."},
        {slug:"etrian-odyssey-4", title:"Etrian Odyssey IV: Legends of the Titan (3DS)", date:"2013-02-26", score:82, scoreType:"critic", hltb:"40h", blurb:"Dungeon-RPG où l'on dessine soi-même sa carte sur l'écran tactile."},
        {slug:"dragons-dogma-dark-arisen", title:"Dragon's Dogma: Dark Arisen (PS3)", date:"2013-04-23", score:87, scoreType:"critic", hltb:"45h", blurb:"Chasse aux chimères et système de pions, l'action-RPG culte de Capcom."},
        {slug:"shin-megami-tensei-4", title:"Shin Megami Tensei IV (3DS)", date:"2013-07-16", score:83, scoreType:"critic", hltb:"45h", blurb:"Apocalypse démoniaque entre royaume médiéval et Tokyo en ruines."},
        {slug:"tales-of-xillia", title:"Tales of Xillia (PS3)", date:"2013-08-06", score:78, scoreType:"critic", hltb:"40h", blurb:"Deux héros au choix pour l'épisode anniversaire des Tales."},
        {slug:"mario-and-luigi-dream-team", title:"Mario & Luigi: Dream Team (3DS)", date:"2013-08-11", score:81, scoreType:"critic", hltb:"30h", blurb:"Les frères plongent dans les rêves de Luigi, démultiplié à l'infini."},
        {slug:"rune-factory-4", title:"Rune Factory 4 (3DS)", date:"2013-10-01", score:78, scoreType:"critic", hltb:"55h", blurb:"Ferme, romance et donjons, le mariage parfait des genres."},
        {slug:"pokemon-x-y", title:"Pokémon X / Y (3DS)", date:"2013-10-12", score:84, scoreType:"user", hltb:"32h", blurb:"Le passage de Pokémon à la 3D, avec Kalos et les méga-évolutions."},
        {slug:"bravely-default", title:"Bravely Default (3DS)", date:"2014-02-07", score:84, scoreType:"user", hltb:"50h", blurb:"Le RPG old-school de Square Enix, avec son système Brave et Default."},
        {slug:"dark-souls-2", title:"Dark Souls II (PS3)", date:"2014-03-11", score:91, scoreType:"critic", hltb:"45h", blurb:"Drangleic et ses cycles de malédiction, suite plus vaste."},
        {slug:"fantasy-life", title:"Fantasy Life (3DS)", date:"2014-10-24", score:84, scoreType:"user", hltb:"40h", blurb:"RPG de vie de Level-5 où l'on enchaîne douze métiers avec bonheur."},
        {slug:"pokemon-omega-ruby-alpha-sapphire", title:"Pokémon Rubis Oméga / Saphir Alpha (3DS)", date:"2014-11-21", score:84, scoreType:"user", hltb:"30h", blurb:"Hoenn refait en 3D, avec l'envol libre à dos de Pokémon."},
        {slug:"persona-q-shadow-of-the-labyrinth", title:"Persona Q: Shadow of the Labyrinth (3DS)", date:"2014-11-25", score:80, scoreType:"critic", hltb:"60h", blurb:"Les castings de Persona 3 et 4 réunis dans un labyrinthe façon Etrian."},
        {slug:"yo-kai-watch", title:"Yo-kai Watch (3DS)", date:"2015-11-06", score:76, scoreType:"critic", hltb:"30h", blurb:"Chasse aux esprits farceurs dans un Japon du quotidien."},
        {slug:"fire-emblem-fates", title:"Fire Emblem Fates (3DS)", date:"2016-02-19", score:82, scoreType:"user", hltb:"30h", blurb:"Deux familles, deux voies : Héritage accessible ou Conquête exigeante."},
        {slug:"bravely-second-end-layer", title:"Bravely Second: End Layer (3DS)", date:"2016-04-15", score:81, scoreType:"critic", hltb:"45h", blurb:"Suite directe de Bravely Default, système de jobs encore affiné."},
        {slug:"dragon-quest-7-3ds", title:"Dragon Quest VII: La Quête des vestiges du monde (3DS)", date:"2016-09-16", score:78, scoreType:"critic", hltb:"60h", blurb:"Remake du géant PlayStation, des îles entières à ramener à la vie."},
        {slug:"smt-4-apocalypse", title:"Shin Megami Tensei IV: Apocalypse (3DS)", date:"2016-09-20", score:84, scoreType:"critic", hltb:"40h", blurb:"Relecture de SMT IV du point de vue d'un chasseur ressuscité."},
        {slug:"pokemon-sun-moon", title:"Pokémon Soleil / Lune (3DS)", date:"2016-11-18", score:80, scoreType:"user", hltb:"35h", blurb:"Direction Alola et ses formes régionales, sans arènes traditionnelles."},
        {slug:"persona-5", title:"Persona 5 (PS3)", date:"2017-04-04", score:92, scoreType:"user", hltb:"90h", blurb:"Les Voleurs Fantômes s'attaquent aux coeurs corrompus, style inégalé."},
        {slug:"fire-emblem-echoes-shadows-of-valentia", title:"Fire Emblem Echoes: Shadows of Valentia (3DS)", date:"2017-05-19", score:86, scoreType:"user", hltb:"30h", blurb:"Remake de Gaiden, doublé intégral et direction artistique superbe."},
        {slug:"monster-hunter-stories", title:"Monster Hunter Stories (3DS)", date:"2017-09-08", score:81, scoreType:"critic", hltb:"35h", blurb:"Monster Hunter en RPG au tour par tour, monstres à élever."},
        {slug:"pokemon-ultra-sun-ultra-moon", title:"Pokémon Ultra-Soleil / Ultra-Lune (3DS)", date:"2017-11-17", score:84, scoreType:"critic", hltb:"35h", blurb:"Version définitive d'Alola, ultime épisode Pokémon de la 3DS."},
        {slug:"the-alliance-alive", title:"The Alliance Alive (3DS)", date:"2018-03-27", score:76, scoreType:"critic", hltb:"35h", blurb:"Hommage aux RPG SaGa, neuf héros sous un ciel confisqué."},
        {slug:"etrian-odyssey-nexus", title:"Etrian Odyssey Nexus (3DS)", date:"2019-02-05", score:81, scoreType:"critic", hltb:"60h", blurb:"Le grand best-of des labyrinthes, adieu de la série à la 3DS."},
        {slug:"persona-q2-new-cinema-labyrinth", title:"Persona Q2: New Cinema Labyrinth (3DS)", date:"2019-06-04", score:78, scoreType:"critic", hltb:"50h", blurb:"Les héros de Persona 3, 4 et 5 piégés dans un cinéma."}
      ]
    }
  }
};

// Exposé en global pour que la page fonctionne aussi ouverte en file://
// (les imports de modules ES sont bloqués hors serveur HTTP).
if (typeof window !== "undefined") window.ODYSSEY_DATA = DATA;
